### ISSUE TITLE
기증 품목 상세 안내의 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#100]
https://donation.theopencloset.net/guide2

![2017-12-11 3 26 45](https://user-images.githubusercontent.com/4696328/33818451-5d41fc46-de88-11e7-9f1a-db5da8a10243.png)

페이지에서 기증 품목 상세 안내를 누르면 이상과 같은 내용이 나오는데요. 아래와 같은 내용으로 변경하고자 합니다.

![- -a4](https://user-images.githubusercontent.com/4696328/33818488-948ad8bc-de88-11e7-9fde-af344b6e747b.jpg)

가능하면 원본 그림과 유사하게 수정할 수 있도록 요청드리는데요. 어려운 부분은 과감히 생략해 주셔도 됩니다!

**Comment by aanoaa** [comment]
![screenshot-2017-12-14](https://user-images.githubusercontent.com/170528/33975193-63c70814-e0d0-11e7-9d58-e587709cd119.png)

새로운 내용으로 넣으면,

지금의 기증품목 안내와 기증품목 상세안내에 중복된 내용이 있어서 제가 뺐습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
