### ISSUE TITLE
기증 신청 버튼을 누르면 오류 페이지가 뜸

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#103]
기증신청 정보를 입력하고 신청버튼을 눌리면 사진과 같은 오류가 발생합니다.

![5a5bf97f58fd6fae5cf11dda01e44347](https://user-images.githubusercontent.com/4696328/34025499-858a8836-e193-11e7-95c3-87c9314ebd93.jpg)

그리고 어제 마감시간부터 중복된 기증신청이 들어오고 있습니다.

![937ff50108f091b5e1d1b10468aa2068](https://user-images.githubusercontent.com/4696328/34025585-f8dc0a26-e193-11e7-818f-0c5e9836aa2f.JPG)

로딩문제로 버튼을 두번 누른 건가 했는데, 기증 품목이 다른 경우가 있어 직접 전화로 확인해보니, 신청 버튼을 누르니 위의 오류 화면이 나와 잘 되지 않은 것으로 생각하고 다른 디바이스로 다시 신청 하셨다고 합니다. 확인 부탁드립니다.

**Comment by 10001if** [comment]
기증신청이 원할하게 진행되지 않는다는 연락이 계속되고 있습니다.. 
이 경우 어떤 정보를 드려야 하는지 이야기 주시면 그 정보에 맞춰 최대한 오류 부분을 확인하도록 하겠습니다.

**Comment by aanoaa** [comment]
죄송합니다.
확인이 늦었습니다.
기증신청후에 발송되는 메일 설정에 오류가 있었습니다.
지금은 고쳐졌습니다.

**Comment by 10001if** [comment]
@aanoaa 확인해주셔서 감사합니다. :)
