### ISSUE TITLE
[비전트레이닝센터] 12월 기증통계 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#104]
12월1일~12월 31일
3개월 동안 비전트레이닝센터에 기증한 의류수 통계 부탁드립니다.

opencloset/opencloset#1252 와 유사한 요청입니다

**Comment by keedi** [comment]
12월 1일에서 12월 31일까지는 1개월인데 3개월이라고 말씀하셔서, 혹시 12월 이외의 달에 대해서도 통계가 필요하신지요?

**Comment by keedi** [comment]
일단 요청하신 12월 통계는 다음과 같습니다. 정확히는 12월 31일까지는 아니고 12월 29일 11시(현 시점 기준)까지입니다. 12월 31일까지 값이 필요하시다면 말씀해주시면 1월 1일 또는 12월 31일 저녁에 한 번 더 뽑으면 됩니다. 더불어 12월 이외 필요하신 나머지 2개월의 기간을 말씀해주세요~

```
+----------+----------+
| category | COUNT(*) |
+----------+----------+
| belt     |        3 |
| coat     |        3 |
| jacket   |        4 |
| pants    |        1 |
| shirt    |       20 |
| shoes    |        3 |
| tie      |        6 |
+----------+----------+
```

**Comment by pingpongworks** [comment]
@keedi 아, 아닙니다. 제가 1달 맞습니다. 주신 걸로 보내면 될 거 같네요. 감사합니다^^

**Comment by keedi** [comment]
넵~ 혹시 12월 31일에 한 번 더 통계를 뽑아드려야 할까요? 아니면 이걸로 충분하신지요? :)

**Comment by pingpongworks** [comment]
오늘은 종무식 날이라 추가로 등록작업이 있을 거 같지 않네요. 충분합니다~
