### ISSUE TITLE
의류 등록시 중복된 코드라는 알림이 나타남

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#106]
https://github.com/opencloset/OpenCloset-Schema/issues/55
https://github.com/opencloset/donation/issues/6

내용을 확인해보니 옷캔, 비백, 비전의 경우 실물 코드를 옷에 붙이지는 않으나 실제 바코드가 발행되고 있는 것으로 이해하고 있습니다. 열린옷장에서 코드 발행 요청을 드리면 마지막 코드 기준으로 다음 코드 순으로 폐기(옷캔, 비백, 비전)되는 의류에 코드가 부여되고 열린옷장에서 코드를 요청하면 그 마지막 코드로 다시 열린옷장에 수량만큼 코드를 발행해 주시는 것으로 이해하고 있는데요.

어제부터 바지 코드가 중복되어 새 옷 등록을 못하는 현상이 발생하고 있습니다. 
P5WB 코드 앞 뒤로 많은 코드가 중복으로 입력을 하지 못하고 있는 상황인데요.
현재는 바지만 중복이 되고 있다고 합니다. 
혹시 코드가 중복으로 발행이 되고 있는지 싶어 문의드립니다.

그리고 조금 이상한 점은

1. 새 옷 등록시 중복코드라는 안내가 나타나
2. 실제로 첫 화면에서 코드번호를 입력하면 의류가 검색되기도 하고 의류가 검색되지 않기도 합니다.
3. 하지만 실제 주소를 clothes/J03Y 입력하면 나타납니다.

@aanoaa 확인 부탁드리겠습니다.

**Comment by 10001if** [comment]
@pingpongworks 에게 상황 전달하도록 하겠습니다. 질문해주시면 답변 부탁드립니다.

**Comment by aanoaa** [comment]
바코드 발행은 이미 말씀해주신 것 처럼 사용되고 있습니다.

아직 코드가 사용되지 않았다면, `/clothes/XXXX` 로 접근했을때 404 Page not found 가 나와야 합니다.
이게 아니라면 실제로 코드가 사용된 것 입니다.
나타난다고 하는 걸 보면 이미 등록된 코드를 재발행했거나 의류코드를 등록할때에 실수가 있지 않았나 싶습니다.
최근에 팬츠 바코드를 발행한 이력을 찾아보겠습니다.

**Comment by aanoaa** [comment]
최근에 팬츠 코드의 발행일은 `2017-08-24` 입니다.
`P5WB,2505-3211` 는 이때 발행한 바코드에 포함되어 있습니다.(933번째)
https://github.com/opencloset/opencloset/issues/1307

2018-03-14 06:00 기준으로 팬츠의 마지막 의류코드는 `P5WY` 입니다.
이것은 최근발행한 1000개의 팬츠코드에 포함되어 있습니다.(956번째)

이건은 시스템의 오류입니다.
발행했을 당시에 1000번째 코드가 P5Y6 이고 이것이 팬츠의 마지막 의류코드로 기록되었어야 합니다.
그 이후로 옷캔/비백/비전/폐기 팬츠가 등록되면 P5Y7, P5Y8, P5Y9, ... 으로 늘어났어야 합니다.
지금은 팬츠의 마지막 코드가 최소한 P5Y6 이상이어야 합니다.

- 발행한 직후에 마지막 의류코드를 잘못 계산했거나 (`script/generate_code.pl`)
- 폐기의류 등록시 의류코드를 갱신하는 코드가 잘못되었을 수 있습니다.

검토해보도록 하겠습니다.

**Comment by aanoaa** [comment]
폐기의류를 등록하고 의류코드를 갱신하는 부분을 시뮬레이션 해봤습니다.
`P5Y6` -> ... -> `P5WY` 가 나타나는지 확인해보기 위해서입니다.

while 문으로 10초이상 돌려봤는데 순차적으로 증가했고 P5WY 가 다시 나타나지는 않았습니다.

발행한 직후 의류코드 갱신하는 부분도 살펴봤는데 이것은 마지막 코드를 print 하고 이 코드를 그대로 저장하고 있습니다.
잘못된 값이 저장되었을 것 같지는 않습니다.

**Comment by aanoaa** [comment]
임의로 팬츠코드를 `UPDATE` 쿼리를 사용해서 수정했고 이게 잘못됐을 수 있습니다.
의류코드가 중복된다고 나온다고 해서 직접 UPDATE 쿼리를 실행한 적이 있었던 것도 같습니다.

**Comment by aanoaa** [comment]
Aㅏ!
옷캔/비백/비전/사용못함 의류를 등록하면서 의류코드를 입력한게 아닌가 싶습니다.

- 옷캔 의류(팬츠)를 등록하면서 `P5WX`(사용가능) 도 같이 입력
- 옷캔 의류가 등록되면서 폐기 의류 코드가 생성되지 않고 입력된 의류코드가 사용됨

이거 같습니다.

고려하지 못한 부분인데 폐기/재활용 의류 등록시에 의류코드를 입력하면 덮어씌어지는 겁니다.

- 이런일이 발생하지 못하도록 예외처리도 해야하고
- 어느 시점에 의류코드가 잘못 업데이트 되었는지 파악해야하고,
- 그 이후에 등록된 의류코드를 올바르게 수정해주어야 합니다.

**Comment by aanoaa** [comment]
혹시나 싶어서 지난번에 발행했던 의류는 4가지 종류를 모두 확인해봤습니다.

- blouse
- jacket
- shirts
- pants

4가지 모두 위와 같은 문제가 이미 발생했습니다.
발행했던 의류코드가 마지막 의류코드에 덮어씌워졌습니다.

**Comment by aanoaa** [comment]
`B29E`, `J70Y`, `P5Y6`, `S402`
이게 지난 발행의 마지막 의류코드 입니다.

정상적이라면 폐기/재활용 의류가 등록되었을때 기대하는 의류코드는 아래와 같습니다.
`B29F`, `J70Z`, `P5Y7`, `S403`
이 의류코드 검색해봤는데 등록된 의류가 없습니다.

발행된 이후부터(혹은 그전부터) 잘못등록하고 사용했다는 뜻입니다.
최근 발행된 의류코드와 재활용/폐기 의류코드가 혼용되어서 사용되고 있습니다.
폐기/재활용 의류를 등록할때에 문제가 발생했을 것 같은데 이게 오늘에서야 발견된 것이 더 신기합니다.

**Comment by aanoaa** [comment]
지금 재활용/폐기 의류가 등록이 제대로 되지 않습니다.
등록에 실패했을때에 에러화면을 나타내고 있지도 못합니다.

**Comment by aanoaa** [comment]
엉망진창입니다.

- 우선 재활용/폐기 의류등록에 실패했을때 적절한 에러 화면이 나타나도록 고치겠습니다.
- 재활용/폐기 의류 등록시에는 입력된 의류코드를 무시하도록 하겠습니다.

데이터를 고치는 건 그 다음입니다.

**Comment by pingpongworks** [comment]
@aanoaa 저는 일단 현재 담당하고 있는 혹은 이전에 담당했던 옷장지기가 재활용/폐기 의류를 잘못 등록하고 있는지 확인해보겠습니다.

**Comment by aanoaa** [comment]
로컬에서 테스트해봤는데, 재활용/폐기의류를 등록할때에 의류코드를 입력한다고 그 의류코드가 반영되지는 않습니다.
다른 가능성을 찾아봐야 합니다.

**Comment by pingpongworks** [comment]
파악해보니까 현재 담당하는 옷장지기가 평소와 다른 방식으로 재활용폐기의류를 등록했던 부분이 있는걸로 파악되는데, 중복코드를 생성했을것 같지는 않습니다. 이부분은 집에 가서 자세히 적겠습니다.

**Comment by aanoaa** [comment]
관리되고 있는 의류의 마지막 코드가 아닌 등록된 의류코드중 가장 높은 코드를 뽑는 쿼리 입니다.

``` sql
SELECT category, code FROM clothes WHERE category = 'bag'       ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'belt'      ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'blouse'    ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'coat'      ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'jacket'    ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'misc'      ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'onepiece'  ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'pants'     ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'shirt'     ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'shoes'     ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'skirt'     ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'tie'       ORDER BY code DESC LIMIT 1;
SELECT category, code FROM clothes WHERE category = 'waistcoat' ORDER BY code DESC LIMIT 1;
```

**Comment by aanoaa** [comment]
궁금한점 입니다.

- 어떻게 자동증가하는 프로그램내의 의류 마지막 코드가 예측을 벗어나서 변경되었는지
- 지난 발행 이전에도 같은 패턴으로 바코드를 발행해서 사용했고 문제가 없었는데, 이번에 무슨 연유로 발생된 것인지

**Comment by aanoaa** [comment]
재활용/폐기 의류등록에 실패했을때 적절한 에러 화면이 나타나도록 수정하였습니다.

> 재활용/폐기 의류 등록시에는 입력된 의류코드를 무시하도록 하겠습니다.

이건 제가 잘못 추측했습니다.
재활용/폐기 의류는 의류코드를 입력하더라도 무시되고 있었습니다.

**Comment by pingpongworks** [comment]
![image](https://user-images.githubusercontent.com/17288038/37437574-3cbe54a4-2831-11e8-88f2-36d007ad8bcd.png)

>재활용/폐기 의류등록에 실패했을때 적절한 에러 화면이 나타나도록 수정하였습니다.
이렇게 수정해주신 거죠? 현재 재활용/폐기 의류 중 `팬츠`를 등록하려고 할 때 이렇게 뜨네요. 
그런데, 나머지 품목은 문제없이 등록되는데 `팬츠`만 에러가 나는 이유가 뭘까요?

**Comment by pingpongworks** [comment]
그리고 팬츠 바코드들 중에는 `재활용/폐기`로 등록된 바코드도 있지만,
스캐너로 찍었을 때 아예 반응을 안 하는 바코드들이 있습니다. 

P5WW
P5WV
P5WU 

위의 바코드들의 경우입니다. 
이유가 뭘까요?

**Comment by pingpongworks** [comment]
>파악해보니까 현재 담당하는 옷장지기가 평소와 다른 방식으로 재활용폐기의류를 등록했던 부분이 있는걸로 파악되는데, 중복코드를 생성했을것 같지는 않습니다. 이부분은 집에 가서 자세히 적겠습니다.

- 원래 방식 : 자켓, 팬츠 등 선택 후 >> 옷캔, 비백 등 선택
- 현재 담당옷장지기 : 자켓,팬츠 등 선택 >> 여성,남성 선택 >>의류컬러 선택 >>옷캔,비백 등 선택

3월 2일부터 담당한 옷장지기가 착각을 해서 이렇게 했다고 합니다. 
위에서 말씀하신대로 "재활용/폐기 의류는 의류코드를 입력하더라도 무시되고 있었습니다."라면 옷장지기의 실수가 이번 바코드 사태에 영향을 미치지는 않았을 거 같은데, 아닐까요?

**Comment by aanoaa** [comment]
네 맞습니다. 옷장지기가 실수할 여지가 없는 부분인 것 같습니다.
파악하는데 좀 더 시간이 필요할 것 같습니다.

등록시에 성별이나 의류컬러등은 상관없습니다.

**Comment by aanoaa** [comment]
최근 발행된 1000개의 팬츠 코드는 P56F(1) ~ P5Y6(1000) 입니다.
그중에 사용된 것은 987개 이고, 그중에 재활용/폐기가 아닌 사용가능으로 등록된 의류는 44개 입니다.

어떻게 이런일이 가능했는지에 대한 제 추측입니다.

- 1000개의 팬츠/자켓/셔츠/블라우스의 바코드 발행을 서버가 아닌 제 PC 에서 하고 전달
- 열린옷장은 바코드를 인쇄하고 1000번째 것부터 사용함 (P5Y6[1000], P5Y5[999], ...)
- 재활용/폐기 의류는 1번부터 증가했고 사용가능 의류는 1000번 부터 등록했는데 이 둘이 만난 것

서버에서 바코드를 생성하지 않았기 때문에 의류코드가 갱신되지 않은 상태입니다.
발행된 바코드의 사용순서는 상관없습니다.
처음과 끝에서 만난거면 1000이 되어야 하는데 987 입니다.
이빨빠진 13개를 찾아봤습니다.
순차적으로 증가했다면 이빨이 빠져서는 안됩니다.



```
SELECT COUNT(*) FROM clothes WHERE category = 'pants' AND code >= '0P56F' AND code <= '0P5Y6';
+----------+
| COUNT(*) |
+----------+
|      987 |
+----------+
SELECT COUNT(*) FROM clothes WHERE category = 'pants' AND code >= '0P56F' AND code <= '0P5Y6' AND status_id NOT IN (45, 46, 47, 57) ORDER BY code;
+----------+
| COUNT(*) |
+----------+
|       44 |
+----------+
-- 사용가능으로 등록된 의류
SELECT code FROM clothes WHERE category = 'pants' AND code >= '0P56F' AND code <= '0P5Y6' AND status_id NOT IN (45, 46, 47, 57) ORDER BY code;
+-------+
| code  |
+-------+
| 0P5WZ |
| 0P5X0 |
| 0P5X1 |
| 0P5X2 |
| 0P5X3 |
| 0P5X4 |
| 0P5X5 |
| 0P5X6 |
| 0P5X7 |
| 0P5X8 |
| 0P5X9 |
| 0P5XA |
| 0P5XB |
| 0P5XC |
| 0P5XD |
| 0P5XE |
| 0P5XF |
| 0P5XG |
| 0P5XH |
| 0P5XI |
| 0P5XJ |
| 0P5XK |
| 0P5XL |
| 0P5XM |
| 0P5XN |
| 0P5XO |
| 0P5XP |
| 0P5XQ |
| 0P5XR |
| 0P5XS |
| 0P5XT |
| 0P5XU |
| 0P5XV |
| 0P5XW |
| 0P5XX |
| 0P5XY |
| 0P5XZ |
| 0P5Y0 |
| 0P5Y1 |
| 0P5Y2 |
| 0P5Y3 |
| 0P5Y4 |
| 0P5Y5 |
| 0P5Y6 |
+-------+

-- 이빨빠진 13개의 코드(의류 등록이 되어있지 않음)
P57H
P57W
P5EF
P5EG
P5FG
P5G1
P5G2
P5G3
P5H1
P5QU
P5QV
P5S9
P5U6
```

**Comment by aanoaa** [comment]
자켓도 같은 패턴으로 찾아봤는데 자켓은 J697(1) ~ J70Y(1000) 사이에 사용가능 의류로 등록된게 없습니다.
아마도 최근 발행 이전에 발행된 바코드를 사용중인게 아닌가 싶습니다.

**Comment by aanoaa** [comment]
셔츠도 없습니다. S38B ~ S402

**Comment by aanoaa** [comment]
블라우스는 B1HN ~ B29E 154개가 등록되었습니다.
팬츠와 마찬가지로 바코드가 높은 순으로 사용중인 것 같습니다.

290개: 재활용/폐기
154개: 사용가능

이라서 아직 둘이 못만났을뿐

**Comment by aanoaa** [comment]
정리하겠습니다.
https://github.com/opencloset/opencloset/issues/1307 에서 

자켓 1000개
팬츠 1000개
셔츠 1000개
블라우스 1000개

바코드를 발행했는데 이때에 저의 실수로 의류코드가 갱신되지 않았습니다.

https://github.com/opencloset/opencloset/issues/1307#issuecomment-324544954
(`--save` 옵션없이 실행시켰습니다.)

그래서 의류코드가 갱신되지 않았지만 다행스럽게도(?) 옷장지기들이 인쇄된 바코드를 역순으로 사용했습니다.
팬츠가 문제가 되는것은 재활용/폐기로 등록한 의류와 사용가능한 의류가 1000개 가까이 등록되면서
본래는 따로 나뉘어져서 사용되었어야할 의류코드가 중복된 것 입니다.

이것을 발견하는 과정에서 의류코드가 중복되었음에도 제대로 에러를 표시하지 못하는 문제가 발견되어서 수정하였습니다.

**Comment by aanoaa** [comment]
해결방법은 위 4개의 의류의 바코드를 갱신하고 범위안의 아직 사용되지 않은 바코드는 폐기합니다.
다시 1000개를 발행해서 사용합니다.

자켓이나 셔츠의 경우 지난번 발행했던 1000개가 아직 쓰여지지 않았습니다.

**Comment by aanoaa** [comment]
이번 작업을 하면서 의류코드를 보는데 잘못등록된 의류코드가 심심찮게 보입니다.

- 아직 발행도 안된 코드가 의류로 등록되었거나
- `0` 과 `O` 가 바뀌어서 사용됐다거나
- 벨트인데 블라우스 코드가 쓰였다거나

등등입니다.

의류 등록할때에는 바코드 리더기를 사용해야 인간의 실수를 줄일 수 있습니다.
잘못사용된 바코드가 있으면 추후에 의류를 등록할때에 중복 에러가 발생할 수 있습니다.
그때에 원인 분석해서 의류코드를 갱신하는 작업을 해야 할 수도 있습니다.

**Comment by aanoaa** [comment]
서버에 의류코드를 갱신했습니다.

``` sql
UPDATE clothes_code SET code = '0B29E' WHERE category = 'blouse';
UPDATE clothes_code SET code = '0J70Y' WHERE category = 'jacket';
UPDATE clothes_code SET code = '0P5Y6' WHERE category = 'pants';
UPDATE clothes_code SET code = '0S402' WHERE category = 'shirt';
```

**Comment by aanoaa** [comment]
```
perl script/generate_code.pl jacket 1000 --save > jacket.csv
perl script/generate_code.pl pants  1000 --save > pants.csv
perl script/generate_code.pl shirt  1000 --save > shirt.csv
perl script/generate_code.pl blouse 1000 --save > blouse.csv

-------------------------------------------------
'-']/ jacket 의류코드가 갱신되었습니다 => J7SQ
-------------------------------------------------
'-']/ pants 의류코드가 갱신되었습니다 => P6PY
-------------------------------------------------
'-']/ shirt 의류코드가 갱신되었습니다 => S4RU
-------------------------------------------------
'-']/ blouse 의류코드가 갱신되었습니다 => B316
```

[의류코드.zip](https://github.com/opencloset/donation/files/1813891/default.zip)

**Comment by aanoaa** [comment]
아래의 인쇄된 바코드는 폐기해주세요.

`B1HN` ~ `B29E`
`J697` ~ `J70Y`
`P56F` ~ `P5Y6`
`S38B` ~ `S402`

**Comment by 10001if** [comment]
@aanoaa 알겠습니다. 폐기하는 바코드는 제외하고 사용하겠습니다~

**Comment by 10001if** [comment]
@aanoaa 그럼 폐기하는 바코드 외에는 기존에 출력한 바코드를 그대로 사용하면 되나요? 압축파일로 올려주신 바코드들은 무엇인가요?

**Comment by 10001if** [comment]
>이번 작업을 하면서 의류코드를 보는데 잘못등록된 의류코드가 심심찮게 보입니다.
>아직 발행도 안된 코드가 의류로 등록되었거나
0 과 O 가 바뀌어서 사용됐다거나
벨트인데 블라우스 코드가 쓰였다거나
등등입니다.
>의류 등록할때에는 바코드 리더기를 사용해야 인간의 실수를 줄일 수 있습니다.
잘못사용된 바코드가 있으면 추후에 의류를 등록할때에 중복 에러가 발생할 수 있습니다.
그때에 원인 분석해서 의류코드를 갱신하는 작업을 해야 할 수도 있습니다.

실수가 발생하지 않도록 다시 한번 공유하겠습니다.

**Comment by aanoaa** [comment]
폐기하는 바코드들은 https://github.com/opencloset/opencloset/issues/1307 에서 발행된 것들입니다.
각 1000개씩입니다.

저때 발행했던 바코드를 폐기해야 하니까 새로 1000개씩 발행했습니다.
이것들은 인쇄해서 사용해주세요.

저의 부주의로 번거롭게해드려서 죄송합니다.

**Comment by 10001if** [comment]
@aanoaa 아닙니다. 저희도 이번 기회에 바코드 관리를 더 꼼꼼히 해야겠다는 생각을 하게 되었습니다.

그런데 
>B1HN ~ B29E
J697 ~ J70Y
P56F ~ P5Y6
S38B ~ S402

1. 위의 바코드를 폐기하고 (이 바코드들은 opencloset/opencloset#1307 에 포함되어 있는 바코드 맞나요?)
2. 그리고 새로 발행해주신 각 1000개씩의 바코드를 다시 사용하면 되는 건가요?

**Comment by aanoaa** [comment]
1. 네 맞습니다.
2. 네 맞습니다.

**Comment by 10001if** [comment]
@aanoaa 답변 감사합니다. 보내주신 코드 새로 발행해서 사용하도록 하겠습니다.

**Comment by pingpongworks** [comment]
@aanoaa 어쨋든 원인도 찾았고 해결방법도 찾았네요! 수고하셨습니다~
