### ISSUE TITLE
[비전트레이닝센터] 4월 재기증의류수 통계 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#108]
- 재기증기관 : 비전트레이닝센터
- 기간 : 2018년 4월 1일~4월 30일 (1개월간)
- 내용 : 열린옷장이 비전트레이닝센터에 기증한 의류수 통계

열린옷장에서 사용하기 힘든 의류를 비전트레이닝센터에 재기증하여 기부금영수증 처리를 받고 있습니다. 2018년 4월부터는 매월 초에 지난 달의 기증의류수 확인서를 비전트레이닝센터에 전달하기로 되었습니다. 5월 4일 (금) 전까지만 통계 부탁드립니다. 

opencloset/opencloset#1252 와 유사한 요청입니다.

**Comment by pingpongworks** [comment]
비전트레이닝센터 4월 기증통계 다시 한번 요청드립니다. 

어느 분이 담당이신지 확실치 않아 @keedi @aanoaa 

두 분 모두에게 다시 한번 요청드립니다. 

통계는 이전처럼 이슈에 코멘트로 주셔도 됩니다.

**Comment by keedi** [comment]
저는 주로 opencloset쪽 이슈를 확인 및 처리하기 때문에 유사한 이슈더라도 donation에 올리시면, 확인이 늦습니다.  그러고 보니 딱히 통계 관련 이슈를 어디에 올려야 한다 명확하게 결정된 곳은 없어 현재 여기저기에 혼재되어 있긴 하군요. 뭔가 통계 관련 채널을 어찌해야할지 고민해보겠습니다. 본 이슈와 같은 경우라면, opencloset에 올려주시면 될듯 합니다.

본 이슈는 여기에다 결과 기록하겠습니다.

**Comment by keedi** [comment]
4월 기증 통계를 확인하는 질의는 다음과 같습니다.

```sql
SELECT
    c.category
    , COUNT(*)
FROM clothes AS c
LEFT JOIN status   AS s ON c.status_id   = s.id
LEFT JOIN donation AS d ON c.donation_id = d.id
WHERE
    c.status_id = 57 -- 45: 옷캔, 46: 비백, 57: 비전
    AND ( YEAR(d.create_date) = 2018 AND MONTH(d.create_date) = 4 )
GROUP BY c.category
; 
```

**Comment by keedi** [comment]
결과는 다음과 같습니다.

```
+----------+----------+
| category | COUNT(*) |
+----------+----------+
| coat     |        1 |
| jacket   |       11 |
| pants    |        6 |
| shirt    |       13 |
| shoes    |        2 |
+----------+----------+
```

**Comment by keedi** [comment]
이상한 부분이 있으면 말씀해주세요~ :)

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다^^
