### ISSUE TITLE
기증신청 후 30일 후까지 기증하지 않는 기증자에게 자동문자 전송 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#109]
기증신청을 하고 박스를 받은 후 기증을 하지 않은 기증자가 2016년 3월~2017년 12월까지 100여명이나 됩니다. 원하는 날짜로 반송신청서비스를 한 후 제대로 반송완료가 되지않아 '반송안함' 상태로 남아있는 기증신청도 20여건 됩니다. 

운송장번호는 유효기간이 발행일로부터 3개월이기 때문에, 유효기간이 지나고 난 후 기증박스를 발송하려다가 우리가 발행했던 운송장번호가 유효하지 않아 문제가 발생되는 일이 종종 있습니다. 

하여, **기증신청일로부터 30일 지났을 때 다음과 같이 자동문자 발송**을 하여 누락이 되지 않도록 하고자 합니다. 

    [사단법인 열린옷장] 000 님, 안녕하세요. 
    1개월 전에 발송해드린 기증상자 잘 받으셨나요? 편하게 기증하시도록 상자 반송 방법을 다시 한번 안내드리고자 연락드렸습니다.

    https://do*****.*********.***/forms/기증서번호/return?authorized=1 
    1. 위 링크를 통해 발송 가능한 날짜를 선택해주세요.
    2. 선택하신 날짜에 기사님이 방문하시면 기증상자를 전달해주세요.

    소중히 보내주신 기증의류와 이야기는 새로운 시작을 준비하는 청년들에게 큰 응원이 됩니다. 감사합니다.

    -모두를 위한 공유옷장, 열린옷장 드림

이렇게 30일이 지났을 때 자동문자를 발송하여 기증에 대해 환기시킨 후, 기증신청일로부터 60일이 지났을 때도 기증을 하지 않았을 때는 '배송완료' '반송안함' 상태에 있는 기증신청서 중 60일 이상 된 것만 담당자가 확인하여 전화를 통해 다시 한번 기증에 대해 환기시키려고 합니다. 

기증박스만 받고 기증하지 않는 기증자에게 
기증신청일로부터 30일 지났을 때 자동문자 발송 부탁드립니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Cron-SMS/issues/34 에서 진행하겠습니다.
