### ISSUE TITLE
2018년 상반기 기증 관련 데이터 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#111]
2018년 1월~6월까지 기증 관련 데이터를 요청드립니다. 
상반기를 결산하며 내부 구성원들과 기증 성과를 공유하고 
기증 관련 활동의 방향성을 점검하고자 합니다. 
요청드리는 데이터는 다음과 같습니다.

**1. 기간 : 2018년 1월 1일~2018년 6월 30일**
**2. 요청 데이터**
- 총 기증 건수
- 월별 기증건수
- 품목별 기증의류수 
- 기증의류 중 활용된 의류의 품목별 수량 
- 기증의류 중 활용되지 못한 의류 수량와 처리된 결과 (폐기/옷캔/비백/비전)
- 전체 기증건수 중 기증메시지가 있는 건수
- 재능나눔 동의를 한 기증자의 수와 재능나눔분야 내용
- 기업기증 기증의류수와 활용의류수 - 현대해상

7월 18일 아침에 성과공유 회의가 잡혀있는데 
제가 17일 화요일에 제주도에 발표하러 출장이 잡혀있어서
7월 15일 (일)까지 부탁 드리겠습니다. 
궁금했던 항목을 적고 보니까 꽤 많네요. 혹시 문의사항 있으시면 말씀해주세요.

**Comment by keedi** [comment]
https://github.com/opencloset/opencloset/issues/1446

아직까지는 언제나처럼 통계 관련해서는 staff 쪽에 남겨주시면 됩니다.

당시 항목이 애매해서 진행하지 않았는데 일단 세부적으로 나온 것 같으니 해당 이슈에서 진행하겠습니다.

**Comment by pingpongworks** [comment]
네네, 알겠습니다^^
