### ISSUE TITLE
기증신청서 "사용자등록" 버튼 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#112]
<img width="711" alt="default" src="https://user-images.githubusercontent.com/17288038/46900546-b9cbc180-cede-11e8-92ab-dc152a2a32e6.png">

forms/1907 기증자의 "사용자등록" 버튼이 눌러도 반응이 없는 오류입니다. 
다른 기증자는 문제없는데 1907 기증신청서만 문제가 발견되었습니다.
원인파악과 오류수정 부탁드립니다. 
기증하신 의류를 등록하지 못하고 대기하고 있습니다.

**Comment by aanoaa** [comment]
```
[Sat Oct 13 11:58:28 2018] [error] name:name has trailing space
```

이름에 공백이 있어서 staff 에서 사용자등록 오류를 응답했습니다.

```sql
SET NAMES utf8;
UPDATE donation_form SET name = '홍xx' WHERE id = xxxx;
```

처럼 쿼리를 실행해서 이름에 공백을 제거하고 해결하였습니다.

이름에 공백이 있을때에는 서버에서 공백을 제거한 뒤에 받아줘도 되지 않을까 싶습니다.
