### ISSUE TITLE
기증신청 목록 페이지에 쿠폰 목록이 추가된 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#114]
<img width="607" alt="default" src="https://user-images.githubusercontent.com/17288038/50068839-cc2de880-020a-11e9-9473-30e16d0fe392.png">

주말에 쿠폰 관련 작업을 한 후에 기증신청 목록 페이지에 쿠폰 목록이 추가되었습니다. 
서울, 안양, 고양, 용인, 군포, 광주, 테스트 삭제 부탁드립니다.

**Comment by aanoaa** [comment]
```sql
SET NAMES utf8;
INSERT INTO `event_type` (`type`, `domain`, `desc`, `create_date`, `update_date`) VALUES ('', 'donation', 'default 기증 이벤트 타입', NOW(), NOW());
UPDATE event SET event_type_id = 5 WHERE id IN (1, 2);
```

을 적용했습니다.

**Comment by pingpongworks** [comment]
네~ 확인했어요. 감사합니다
