### ISSUE TITLE
[기증 통계] 2019년 기증 관련 데이터 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#119]
2019년 마지막 뉴스레터를 준비하고 있습니다. 
아래 데이터 부탁드립니다. 

1. 2019년 9월 2일 ~ 2019년 12월 16일 
   기증자 성명, 이메일주소

2. 2019년 1월 1일 ~ 12월 16일 
    총 기증 건수

3. 2019년 1월 1일 ~ 12월 16일 
    품목별 기증 의류수  (자켓/바지/치마/셔츠/블라우스/타이/벨트/구두/원피스/코트/기타)

4. 2019년 1월 1일 ~ 12월 16일 
    기증편지 수 / 대여편지 수

12월 20일 (금) 오전까지 부탁드립니다.

**Comment by aanoaa** [comment]
2019년 9월 2일 ~ 2019년 12월 16일
기증자 성명, 이메일주소

    #!/bin/sh
    username=xxxxxxxxx
    password=xxxxxxxxx
    database=xxxxxxxxx
    
    mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > donation-list.csv
    SELECT
      df.name,
      df.email
    
    FROM donation d
    
    JOIN donation_form df ON d.id = df.donation_id
    
    WHERE df.status IN ('registered', 'return-requested', 'returned', 'returning')
    AND d.create_date BETWEEN '2019-09-02' AND '2019-12-17'
    
    ORDER BY d.create_date
    EOF

2019년 1월 1일 ~ 12월 16일
총 기증 건수

    #!/bin/sh
    username=xxxxxxxxx
    password=xxxxxxxxx
    database=xxxxxxxxx
    
    mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > donation-cnt.csv
    SELECT COUNT(1) AS '총 기증 건수' FROM donation WHERE create_date BETWEEN '2019-01-01' AND '2019-12-17'
    EOF

2019년 1월 1일 ~ 12월 16일
품목별 기증 의류수 (자켓/바지/치마/셔츠/블라우스/타이/벨트/구두/원피스/코트/기타)

    #!/bin/sh
    username=xxxxxxxxx
    password=xxxxxxxxx
    database=xxxxxxxxx
    
    mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > donation-categories.csv
    SELECT c.category AS '카테고리', COUNT(c.category) AS '건수'
    FROM clothes c
    JOIN donation d ON c.donation_id = d.id
    WHERE d.create_date BETWEEN '2019-01-01' AND '2019-12-17'
    GROUP BY c.category
    EOF

2019년 1월 1일 ~ 12월 16일
기증편지 수 / 대여편지 수

    #!/bin/sh
    username=xxxxxxxxx
    password=xxxxxxxxx
    database=xxxxxxxxx
    
    mysql -u $username -p$password -h 0.0.0.0 $database <<EOF | sed 's/\t/,/g' > donation-letter-cnt.csv
    SELECT d.cnt AS '기증편지 수', o.cnt AS '대여편지 수'
    FROM (
      SELECT 1 AS tmp, COUNT(*) AS cnt
      FROM donation AS d
      WHERE
        d.create_date BETWEEN '2019-01-01' AND '2019-12-17'
        AND d.message IS NOT NULL
    ) d
    LEFT JOIN (
      SELECT 1 AS tmp, COUNT(*) AS cnt
      FROM \`order\` o
      WHERE
        o.create_date BETWEEN '2019-01-01' AND '2019-12-17'
        AND o.message IS NOT NULL
    ) o
    ON d.tmp = o.tmp
    EOF

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/1513 를 참고했습니다.
결과는 메일로 전달드렸습니다.
