### ISSUE TITLE
상태가 변경되어도 문자 발송이 되지 않도록 하게함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#13]
기증자 분이 반송신청을 직접 하신 경우가 있었는데, 이 경우에는 반송신청에서 반송 중으로 바뀔 때 자동으로 발송되는 문자를 보내지 않도록 선택하는 기능이 있었으면 좋겠다는 의견이 있었습니다..

**Comment by aanoaa** [comment]
직접 반송신청을 하셨다면 열린옷장에 `반송신청` 을 하실 필요가 없습니다.

열린옷장에 반송신청을 하고 `배송완료` -> `반송신청`
직접 반송하시면 문자메세지를 받는 케이스입니다.

열린옷장에 반송신청을 하지않고 직접 반송하실때에는
`배송완료` 상태에 머물게 됩니다. 이때 `반송중` 으로 staff 이 변경하면 문자메세지를 받지 않습니다.

열린옷장에 반송신청하고 직접 반송하시는 경우에 문제가 되는 건가요?

**Comment by aanoaa** [comment]
신청서의 상태는 순서가 있는 것 처럼 보이지만 사실은 전혀 상관없습니다.
`신청됨` -> `등록됨` 역시 가능합니다.

**SMS 가 전송될때** 이외의 상태변화에 대해서는 SMS 가 발송되지 않습니다.
`배송완료` -> `반송중` 에는 상태만 변경되지 `반송신청 -> 반송중` 의 SMS 가 발송되지 않는다는 얘기입니다.

**Comment by 10001if** [comment]
@aanoaa 이해가 되었습니다. 설명해 주신 내용으로 적용된다면 문제가 없을 것 같습니다. 본 이슈는 내일 공유가 필요할 것 같아 확인요망 라벨을 붙이겠습니다. 내일 확인 후 제거하도록 하겠습니다.
