### ISSUE TITLE
운송장 번호가 화면에서 바로 보이도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#14]
![2016-03-24 3 32 30](https://cloud.githubusercontent.com/assets/4696328/14010133/d0d1f8ce-f1d5-11e5-9a23-e44d8d5b2d0c.png)
현재는 운송장 번호를 확인하려면 운송장 번호 변경 버튼을 눌러야 하는데, 번호가 바로 보였으면 좋겠다는 요청이 있습니다. 수정 요청드립니다~

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/764

**Comment by aanoaa** [comment]
4자리마다 `-`로 끊어서 보여주어야 하나요?
