### ISSUE TITLE
기증시 특정기업 임직원만 기증할 수 있는 통로 개설

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#141]
#107 참고

S기업 전직원 기증캠페인에 필요할 수 있어서 기존의 #107 이슈에서 만들었던 기능의 테스트를 요청합니다.

1) 이벤트 기증신청 페이지에 'S기업 정장기증 캠페인에 참여하는 임직원이십니까? (해당되는 경우만 체크해주세요)'체크박스 삽입
2) staff 기증신청 목록 페이지에서 'S기업' 탭 배치하여 클릭하면 따로 분류해서 볼 수 있어야 함
3) 끝난 후에 S기업 기증자의 기증의류 수를 따로 통계내어 전달해야함

테스트 페이지로 논의 후 진행을 결정해보려고 합니다.

**Comment by pingpongworks** [comment]
@aanoaa 님이 기존 기능을 되살려서 테스트 페이지를 만들어 주셨습니다. 

일반 기증과정과 동일하나 
`✅ 열린그룹에서 진행하는 기증캠페인` 인지 여부에 체크할 수 있도록 만들었습니다.
이 페이지를 통해서 기증신청이 들어오는 경우 특정기업 기증건만 따로 분류가 가능합니다. 

https://donation.theopencloset.net/redirect?event_id=1

<img width="1168" alt="스크린샷 2023-07-25 오후 1 21 52" src="https://github.com/opencloset/donation/assets/17288038/1c34bb15-0c06-482f-8264-66c0e60fa1ca">

현재 이 페이지로 기증캠페인 예정 기업과 논의중입니다. 

결정이 되면 다음 작업이 필요할 수 있습니다. 
- 기업명과 문구 수정
- 첫 페이지 기증안내 내용이나 이미지 교체

현재 기증캠페인 예정일정은 빠르면 8월 2주차 (8월 7일) 부터입니다.
일단 상황 공유드립니다.

**Comment by pingpongworks** [comment]
@aanoaa 님이 DB 접근이 어려워서 staff 페이지의 메뉴 수정은 @ooooopen 님에게 요청해야 할 듯 합니다.

**Comment by pingpongworks** [comment]
8월 7일부터 기증캠페인 진행이 결정되어 문구와 이미지 수정 부탁드립니다. 

1. 체크박스 문구 기업명 넣어서 수정 : 잘 보이도록 볼드처리 부탁드립니다. 

✅ **삼성전자 기증캠페인에 참여하는 임직원이신가요?** (해당되는 경우만 체크해주세요)
 

2. 첫 페이지 이미지 교체 (ai파일 필요하면 요청해주세요)

![image](https://github.com/opencloset/donation/assets/17288038/77fc9c62-6a2b-4fc6-a3d3-fc0a6616e82e)


8월 1일 (화)까지 작업 부탁드립니다.

**Comment by aanoaa** [comment]
이미지를 교체하는 것에 대한 고려가 없습니다.
기증페이지의 다른 모든 것이 같고, 신청란에 추가된 문구만을 노출할 수 있습니다.

거기에 통계 수집과 전용목록 기능만을 고려했을 뿐 입니다.

특정기업에 대해서만 랜딩페이지를 다르게 하기 위해서는 개발이 필요합니다.

**Comment by pingpongworks** [comment]
![IMG_8197](https://github.com/opencloset/donation/assets/17288038/865a0912-96c4-4067-8c84-2c95e67016ad)
이 페이지는 현재 일반 기증자에게는 노출되지 않고 있습니다. 다음 페이지부터 노출되고 있어서 특정기업에 대해서만을 위한 개발없이 페이지 내용 수정만 해주시면 됩니다. 이미지 교체 불가능할까요?

**Comment by pingpongworks** [comment]
작업 완료 되었습니다. 감사합니다.
