### ISSUE TITLE
기증내역 통계요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#143]
S기업 기증캠페인이 종료되어서 기증자별, 기증품목별 통계를 요청합니다. 

- 기간 : 2023년 8월 7일 ~ 9월 1일
- 대상 : 기간내에 기증자로 등록된 사용자
- 내역 : 기증자명 / 휴대폰번호 / 이메일주소 / 주소 / 기증품수 (품목별) / 의류등록상태 (열린옷장 / 옷캔 / 폐기)

**Comment by bek9** [comment]
https://opencloset-seeso.slack.com/archives/C0529EEME5D/p1693554372261399?thread_ts=1693530215.778639&cid=C0529EEME5D
