### ISSUE TITLE
배송이 완료된 택배의 상태 자동변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/donation#2]
운송장 번호가 입력되고 택배가 발송된 후에 polling 해서
`배송중` -> `발송완료` 상태로 변경해야 합니다.

**Comment by aanoaa** [comment]
GET https://www.doortodoor.co.kr/parcel/doortodoor.do?fsp_action=PARC_ACT_002&fsp_cmd=retrieveInvNoACT&invc_no=12345678
    SSL connection failed for www.doortodoor.co.kr: SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by aanoaa** [comment]
일단 이 문제를 해결해야 합니다.
doortodoor.co.kr 의 인증서에 문제가 있는 거 같은데 이거 뭐야 무서워

    $ curl --insecure "https://www.doortodoor.co.kr/parcel/doortodoor.do?fsp_action=PARC_ACT_002&fsp_cmd=retrieveInvNoACT&invc_no=12345678"
    curl: (35) gnutls_handshake() failed: Handshake failed

**Comment by aanoaa** [comment]
인증서 문제 해결되었습니다.
저쪽 서버에서 서버 패키지 업그레이드 한듯

**Comment by yongbin** [comment]
와드

**Comment by aanoaa** [comment]
와드가 뭔가여?
이거 제가 고객문의 넣긴 했습니다 답변은 못받았지만서도

**Comment by yongbin** [comment]
온라인쪽에서도 비슷한 논의가 있어서요 어떻게 진행되는지 노티받으려고 덧글 달았습니다. (보통 이런경우 페북에서 사람들이 "와드박고 갑니다" 라고 쓰더라구요)

**Comment by aanoaa** [comment]
롤에서 와드 박아놓으면 시야가 보이니까 하는 말인 듯

**Comment by aanoaa** [comment]
이게 github 에서는 watch 하고 있는 프로젝트는 알아서 노티가 간다 아입니까?
와드 박고 다닐 필요없습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/donation/blob/develop/bin/delivering2delivered.pl 스크립트를 cron 에 등록시켜줘야 합니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/donation/blob/develop/lib/OpenCloset/Donation/Command/update_status.pm

를 대신 사용하도록 해서 해결하였습니다.
서버에 크론으로 등록도 해두었습니다.
