### ISSUE TITLE
새옷 등록시 바지 밑단 둘레 항목을 입력할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#20]
의류 정보에 추가해주셔서 감사합니다. 새 옷 등록시 바지 밑단 둘레를 입력 할 수 있도록 요청드립니다. ^^

**Comment by aanoaa** [comment]
이미 그렇게 되어있습니다.

**Comment by 10001if** [comment]
@aanoaa 죄송합니다~ 기존의 새옷등록 절차에 나타나지 않아서 적용이 되지 않은 것으로 생각하고 있었나봐요~ 확인하였습니다. ^^
