### ISSUE TITLE
새옷 등록시 바지 밑단둘레 항목의 기본 단위를 inch로 변경 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#29]
현재는 cm단위로 설정되어 있습니다. 하지만 기본단위를 inch로 변경 요청드립니다.
그리고 `밑단 둘레`에서 `밑단`으로 수정 요청드립니다.

변경하려는 이유는 수선에 대한 이슈가 가장 큰 이유입니다. 그 내용은 다음과 같습니다.

1. 일반적으로 의류의 경우 cm로 수선을 요청하는 것이 가능함
2. 하지만 밑단의 경우 inch로만 의사소통이 가능한 것으로 확인
3. 때문에 cm로 표기하더라도 수선을 위해 다시 inch로 변경해야 하는 어려움 발생
4. 기록은 cm로 하고 수선 시에만 inch로 변경하는 방안을 생각해 봤으나 변환의 어려움이 있을 것으로 예상됨
5. 또한, cm 와 inch 변환시 반올림, 반내림 등으로 절삭되는 정보들이 발생하고 있는 문제가 발생

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/789

**Comment by yongbin** [comment]
기존에 의류사이즈는 모두 통일해서 cm로 저장하고 있습니다. 따라서 가능하다면 사용자에게는 inch를 보여주더라도 DB에는 cm로 저장되는 형태로 진행되었으면 좋겠습니다.

**Comment by aanoaa** [comment]
```perl
use strict;
use warnings;
my $regex = qr/^\d{1,3}(\.)?(\d{1,2})?$/;

for my $num (qw/9 10 123 10.1 1.12 1.12 100.1 100.12 100.898 .90/) {
    print "$num\n" unless $num =~ /$regex/;
}
__DATA__
100.898
.90
```

뭐 맞겠지 싶습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Schema/issues/59 를 해결하고 있는데,

cm 로 저장되어야 할 `cuff` 가 `inch` 로 저장되어 있는 자료를 발견했습니다.

https://staff.theopencloset.net/clothes/P1KN

**Comment by aanoaa** [comment]
아이고 변환되어서 나타난걸 잘못저장된줄 착각했습니다.

**Comment by aanoaa** [comment]
설상가상으로 테스트해본다고 제가 이리저리 바꾸어봤던 의류를 보고 있었습니다.
