### ISSUE TITLE
배송완료시에 발송되는 문자 내용 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#31]
김소령 기증자님, 안녕하세요. 열린옷장입니다. 

보내드린 기증상자 잘 받으셨나요? 열린옷장의 '참~쉬운' 기증방법 안내해드리겠습니다. 

1. 기증상자에 의류를 담는다.
2. '나의 정장 기증이야기'를 작성한다.
3. 아래 링크로 기증상자를 수거해갈 날짜를 선택한다. 
4. **선택한** 날짜에 방문한 CJ택배 기사님께 기증상자를 전달한다. 

보내주시는 기증의류와 **이야기는** 열린옷장을 ****찾아오신 많은 분들에게 큰 응원으로 전달됩니다. ** **

- 모두를 위한 공유옷장, 열린옷장

**Comment by aanoaa** [comment]
@pingpongworks 이것도 마찬가지고 정확한 텍스트를 적어주세요.

**Comment by pingpongworks** [comment]
위에 적은 게 정확한 텍스트입니당~ 볼드체로 된 것만 수정해주심 됩니다~

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/798

**Comment by aanoaa** [comment]
```
김소령 기증자님, 안녕하세요. 열린옷장입니다. 

보내드린 기증상자 잘 받으셨나요? 열린옷장의 '참~쉬운' 기증방법 안내해드리겠습니다. 

1. 기증상자에 의류를 담는다.
2. '나의 정장 기증이야기'를 작성한다.
3. 아래 링크로 기증상자를 수거해갈 날짜를 선택한다. 
4. 선택한 날짜에 방문한 CJ택배 기사님께 기증상자를 전달한다. 

보내주시는 기증의류와 이야기는 열린옷장을 찾아오신 많은 분들에게 큰 응원으로 전달됩니다.

- 모두를 위한 공유옷장, 열린옷장
```

위 내용으로 수정하겠습니다.

**Comment by aanoaa** [comment]
문제가 있습니다.
수거날짜 선택하는 링크가 없습니다.

**Comment by aanoaa** [comment]
```
김소령 기증자님, 안녕하세요. 열린옷장입니다. 

보내드린 기증상자 잘 받으셨나요? 열린옷장의 '참~쉬운' 기증방법 안내해드리겠습니다. 

1. 기증상자에 의류를 담는다.
2. '나의 정장 기증이야기'를 작성한다.
3. 아래 링크로 기증상자를 수거해갈 날짜를 선택한다.

https://donation.theopencloset.net/forms/8/return?authorized=1

4. 선택한 날짜에 방문한 CJ택배 기사님께 기증상자를 전달한다. 

보내주시는 기증의류와 이야기는 열린옷장을 찾아오신 많은 분들에게 큰 응원으로 전달됩니다.

- 모두를 위한 공유옷장, 열린옷장
```

위 내용으로 수정하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 저희가 내용을 빠뜨렸었네요. 챙겨주셔서 감사드려요~ ^^
