### ISSUE TITLE
새옷 등록 후 수선 절차를 진행할 수 있는 프로세스를 추가하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#33]
![default](https://cloud.githubusercontent.com/assets/4696328/14732521/78ab8994-0896-11e6-8d18-e7bdf4b77327.png)

수선을 어떻게 하는지 확인해 본 결과 다음과 같은 절차로 진행이 됩니다.

기본적으로는 가이드 화면을 보고 알아서 수선치수를 입력 할 수 있도록 하는 게 좋겠지만
가능하다면 수선해야 할 사이즈를 예측하여 의류 사이즈가 수선치수로 변경되고 변경된 사이즈가 수선표로 출력되어
의류를 등록 함과 동시에 수선업체에 전달 할 수 있다면 좋겠습니다.

그리고 본 과정에서 수선으로 상태가 변경되는 의류는 수선신청일, 수선업체, 수선수거일, 수선비용 등을 체크할 수 있다면 좋겠습니다. 본 이슈는 @aanoaa 께 다시 여쭤보고 정리를 하는 것이 필요할 것 같습니다.. ^^;

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/802

**Comment by 10001if** [comment]
![image](https://cloud.githubusercontent.com/assets/4696328/14732923/d006613e-0899-11e6-958f-2bd6c2e0b31d.png)

**Comment by 10001if** [comment]
![image](https://cloud.githubusercontent.com/assets/4696328/14732930/db44525e-0899-11e6-9a78-950ba5db3214.png)

**Comment by aanoaa** [comment]
ㄲ ㅑ~

**Comment by aanoaa** [comment]
이전에 수선이 필요한 의류가 새옷등록 후에 상태가 어떤식으로 바뀌는지
생각해봐야 합니다.

- 새옷등록(바지)
- 상태를 수선으로 변경
- 실제로 수선
- 치수측정 후에 사이즈 변경
- 상태를 대여가능으로 변경

@10001if 이게 맞나요?

**Comment by aanoaa** [comment]
여기서 해결해야 하는 것이 **치수측정 후에 사이즈 변경** 을 자동으로
하는 것입니다.

실제로 사용되기 위해서

`수선` 상태인 의류에 대해 `치수변경`? 버튼을 둬서 누르면 위 그림에 맞게끔
수정된 사이즈가 사용자에게 제안되고, 사용자는 확인을 눌러서 사이즈를
변경

정도로 생각해 볼 수 있습니다.

더 나은 제안이 있다면 알려주시기 바랍니다.

**Comment by aanoaa** [comment]
새옷등록과는 상관이 없습니다.
재고관리의 의류 화면에서 해결되어야 합니다.

**Comment by aanoaa** [comment]
> 새옷등록(바지)
> 상태를 수선으로 변경
> 실제로 수선
> 치수측정 후에 사이즈 변경
> 상태를 대여가능으로 변경

여기에서 실제수선후에 치수측정을 하는 것이 아니라,
미리 사이즈를 바꿔놓는다고 합니다.

수선완료인 옷에 대해서 사이즈를 재입력할 필요가 없습니다.
재고관리와 새옷등록 어느곳에서건 편리하게 바꿀 수 있으면 됩니다.

**Comment by aanoaa** [comment]
수선에 관한 목록이 있고 거기에서 관련된 작업을 하였으면 합니다.

구체적인 내용은 미정이라서 제가 알아서 스슥하고 피드백 받겠습니다.

**Comment by aanoaa** [comment]
쌍이 없는 것은 수선하지 않는다고 합니다.

**Comment by 10001if** [comment]
@aanoaa 남성의 경우에는 수선하지 않고 여성의 경우에는 쌍의 개념이 없고 단품으로 개별으로 수선을 진행합니다. 따라서 쌍이던 단품이던 수선은 진행합니다. 그런데 의류에는 성별이 없다고 하셔서 어떻게 구별하는지 잘 모르겠지만, 새 옷을 등록할 때는 남성용, 여성용, 남여공용을 입력하는 것으로 알고 있습니다. 이 부분은 성별 구분과는 관계가 없는 것인지 궁금합니다.

**Comment by aanoaa** [comment]
제가 잘못알았습니다.
의류에 성별이 있습니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2016-04-28 17-39-25](https://cloud.githubusercontent.com/assets/170528/14880120/36d5d19c-0d68-11e6-8987-de5c0bf816f5.png)

샘플입니다.

수선의류목록을 만들고자 하는데 실제 작업절차에 따라서 필요한 값들을 보여줘야 합니다.
@10001if 확인해보시고 의견주세요.

**Comment by 10001if** [comment]
@aanoaa 어제 이야기 주신 그림과 동일하네요. 치수변경 버튼은 이해가 되었는데, 미리보기 버튼이 어떤 역할을 하는지 궁금합니다~ ^^

**Comment by aanoaa** [comment]
이미 수선을 했는지 여부가 필요합니다.

**Comment by aanoaa** [comment]
이미 수선했는지에 대한 여부는 현재의 schema 로는 저장 할 수 없습니다.

의류 for 수선
의류 for 폐기

와 같은 테이블을 추가해 나갈까 합니다.

**Comment by yongbin** [comment]
도움이 되실지는 모르겠지만 `order_status_log`를 이용하면 수선상태였던 주문서를 알수는 있습니다.

**Comment by aanoaa** [comment]
네 하지만 수선상태였엇던 주문서는 필요없습니다.

**Comment by aanoaa** [comment]
- 허리늘림 가능
- 턱이 있어 추가늘임 가능
- 1턱일 경우
- 2턱일 경우

이런 경우는 현재의 시스템상으로 고려할 수 없습니다.
추가적인 데이터 입력이 필요합니다.

계산식의 옵션으로써 선택할 수 있도록 할 수는 있습니다.

**Comment by aanoaa** [comment]
- 밀라노 사장님께 여쭤본후 판단

ㅋㅋ 이런거 어쩝니까..

**Comment by aanoaa** [comment]
요구에 따르면 허벅지둘레에 따라 밑통을 입력해야 하는데,
표를 보시면 `70` 일때에 밑통은 `7.50` 또는 `7.75` 입니다.

그에 반해 허리사이즈로는 밑통을 알 수 있습니다.
허리둘레에 따라 밑통을 입력해도 될까요?

**Comment by aanoaa** [comment]
1턱일 경우는 허리늘임이 어려운 경우인데 그 이후에
`윗배 - 허리 = 9 가능` 은 무슨 뜻인가요?

**Comment by aanoaa** [comment]
상하의 셋트의류가 등록되고,
팬츠를 수선할때에 자켓도 같이 수선하나요?
셋트의류가 등록되어 있으면 팬츠/자켓에 대한 두벌의 리사이즈가 되어야
하나요?

**Comment by aanoaa** [comment]
총장에 따른 팔길이를 참고할 만한 자료가 없습니다.

**Comment by aanoaa** [comment]
자켓의 경우 `윗배 - 허리` 가 `9` 또는 `10` 일때에는 어떻게 되나요?

**Comment by aanoaa** [comment]
남자 > 자켓 > `윗배 - 허리 > 10` 일때에
`가슴 - 윗배 = 0 --- 4cm 줄임 가능`

이런것들에 대한 의미를 모르겠습니다.

**Comment by aanoaa** [comment]
여자 > 자켓

에서 윗배에 따라 팔길이 수선이지만 참고할만한 자료가 없습니다.

**Comment by aanoaa** [comment]
치수대비표를 보면 허벅지, 엉덩이등은 짝수로만 입력되어 있는데,
(88, 90 등등) 홀수 일때는 어떻게 되나요?(89일때)

1cm 단위가 필요합니다.

**Comment by aanoaa** [comment]
@10001if 수선표를 보고 작업하려 했는데 부족한 부분이 보입니다.
위에 궁금한 점들을 남겨놓았습니다. 읽어보시고 답변해주세요.

**Comment by 10001if** [comment]
![image](https://cloud.githubusercontent.com/assets/4696328/14977672/fb6f4498-1150-11e6-81df-3500e02a2862.png)

**Comment by aanoaa** [comment]
`윗배 - 허리 < 9` 는 `팬츠가 수선이 되었다면` 으로 읽습니다.
`윗배 - 허리 > 10` 는 `팬츠가 수선되지 않았다면` 으로 읽습니다.

**Comment by aanoaa** [comment]
> 가슴 - 윗배 = 0 --- 4cm 줄임 가능

이거는 `윗배 = 가슴 - 4` 로 변경해야 함을 뜻합니다.

**Comment by aanoaa** [comment]
- 남자 > 바지 > 어려움 > 1턱 > 9 어려움일때는 무시
- 팬츠가 resizing 되었다면 자켓도 수정되어야 함(100% 라고함)
  - 미리보기가 하의 상의별로 보여지고 둘다 업데이트 되어야 합니다
- 수선완료 했을때가 수거일임
- 목록에 바코드 검색이 가능하도록

**Comment by aanoaa** [comment]
- 치수변경은 한번만 가능
- 치수가 변경되면 `치수변경` 버튼 대신에 현재 치수를 보여준다

**Comment by aanoaa** [comment]
치마 허리의 before after 가 10cm 이상 차이나면, *치마 통 수선* 을 표시해줘야합니다.

**Comment by 10001if** [comment]
**비용**
`허리늘임/줄임 : 5000원`
`턱늘임 : 25000원`
`허벅지 수선 : 5000원`
`밑통 수선 : 5000원`
`윗배줄임 : 10000원`
`팔길이줄임 : 5000원`
`기장줄임 : 5000원`

**Comment by aanoaa** [comment]
- *남자* > *바지* > *윗배 - 허리 < 5cm*
  - 허리수선: 윗배 - 7
  - 허벅지수선
  - 밑통수선
- *남자* > *바지* > *윗배 - 허리: 5cm ~ 8cm*
  - 허벅지수선
  - 밑통수선
- *남자* > *바지* > *윗배 - 허리 > 8cm*
  - 허리수선: 윗배 - 9
  - 허벅지수선
  - 밑통수선
- *남자* > *바지* > *윗배 - 허리 > 8cm* > *허리늘임 어려움* > *1턱일 경우*
  - 허리 += 4cm
  - *윗배 - 허리 > 10cm*
    - 허벅지수선?
    - 밑통수선?
  - *윗배 - 허리 <= 10cm*
    - 허리수선: 윗배 - 9
    - 허벅지수선?
    - 밑통수선?
- *남자* > *바지* > *윗배 - 허리 > 8cm* > *허리늘임 어려움* > *2턱일 경우*
  - 허리 += 8cm
  - *윗배 - 허리 > 10cm*
    - 허벅지수선?
    - 밑통수선?
  - *윗배 - 허리 <= 10cm*
    - 허리수선: 윗배 - 9
    - 허벅지수선?
    - 밑통수선?

---------------------------------------------

- *남자* > *자켓* > *허리수선됨*
  - 팔길이 수선
- *남자* > *자켓* > *허리수선 안됨*
  - 윗배수선

**Comment by aanoaa** [comment]
클리어해졌습니다.
팬츠의 수선은 윗배를 기준으로 허리를 줄이거나 늘입니다.

    허리 = 윗배 - 9

줄이는건 상관없지만 늘일때가 문제가 됩니다.

팬츠에 따라 허리를 늘일 수 있는지 여부가 결정됩니다.

- 팬츠 뒤쪽에 `허리늘임` 이 가능한경우 (+ ?cm)
- 턱이 있는 경우
  - 턱이 1개 있는 경우 (+ 4cm)
  - 턱이 2개 있는 경우 (+ 8cm)

해서 구분해보면 팬츠에는 4종류가 있습니다.

- `허리늘임`이 불가능하고 턱이 없는 팬츠
- `허리늘임`이 불가능하고 턱이 있는 팬츠
- `허리늘임`이 가능하고 턱이 없는 팬츠
- `허리늘임`이 가능하고 턱이 있는 팬츠

최대한으로 늘이고도 `윗배 - 허리 > 9` 라면 `가슴 - 윗배` 를 기준으로
쌍이 되는 자켓의 윗배를 줄입니다.

턱은 일반적으로 `4cm` 로 계산할 수 있지만, `허리늘임`은 다릅니다.
팬츠마다 다르기 때문입니다.

해서 `허리늘임` 옵션은 `cm` 단위로 입력해서 계산할 수 있도록 해야 합니다.

**Comment by aanoaa** [comment]
남성 자켓의 경우 총장에 따른 팔길이에 대한 정보가 없습니다.

**Comment by 10001if** [comment]
![image](https://cloud.githubusercontent.com/assets/4696328/15005804/4de3f7f6-1204-11e6-8506-1e01a27f3c22.png)
남자자켓 총장대비 팔길이 표입니다.

**Comment by 10001if** [comment]
총장 _ 팔
 60   _ 50  
 62   _ 51
 64   _ 52
 66   _ 53
 68   _ 54
 70   _ 56
 72   _ 58
 74   _ 60
 76   _ 61
 78   _ 62
 80   _ 64
 82   _ 66
 84   _ 67
 86   _ 68
 88   _ 69
 90   _ 70

**Comment by aanoaa** [comment]
사이즈 map 에 관한데이터를 table 로 정리해서 전달

**Comment by aanoaa** [comment]
- 수선의류 목록에 의류의 상태도 나타냄
- 수선사유? 에 관한 컬럼 추가
- 치수변경된 의류는 제안이 아니라 실제 사이즈를 보여줌

**Comment by aanoaa** [comment]
수선장소마다 수거하지 못한 의류를 파악해야 하기 때문에,
수선장소마다 수거일로 정렬해서 보여줘야 합니다.

수거일이 없다면? 아직 수거가 안된 것

하지만 두번이상 수선이 이루어 질 수 있으므로, 수거일이 없는 것만
찾아서는 아니됩니다.

**Comment by aanoaa** [comment]
검색을 여러벌 동시에 가능하도록 해야 합니다.
stack 에 쌓이는 것 처럼..

바코드를 일단 쭈욱 찍고 그 이후에 진행상태를 업데이트 할 것이기
때문입니다.

**Comment by aanoaa** [comment]
의류가 특정상태가 아닐때(대여중 이라거나..) 수선장소가 입력되면 의류의
상태를 `수선` 으로 변경

**Comment by aanoaa** [comment]
> 사이즈 map 에 관한데이터를 table 로 정리해서 전달

| 허리  | 허벅지 | 
|-----|-----| 
| 78  | 58  | 
| 79  | 59  | 
| 80  | 60  | 
| 81  | 61  | 
| 82  | 62  | 
| 83  | 63  | 
| 84  | 64  | 
| 85  | 64  | 
| 86  | 64  | 
| 87  | 65  | 
| 88  | 66  | 
| 89  | 67  | 
| 90  | 68  | 
| 91  | 68  | 
| 92  | 68  | 
| 93  | 69  | 
| 94  | 70  | 
| 95  | 70  | 
| 96  | 70  | 
| 97  | 70  | 
| 98  | 70  | 
| 99  | 71  | 
| 100 | 72  | 
| 101 | 72  | 
| 102 | 72  | 
| 103 | 72  | 
| 104 | 72  | 
| 105 | 73  | 
| 106 | 74  | 
| 107 | 74  | 
| 108 | 74  | 
| 109 | 75  | 
| 110 | 76  | 
| 111 | 76  | 
| 112 | 76  | 
| 113 | 77  | 
| 114 | 78  | 
| 115 | 78  | 
| 116 | 78  | 
| 117 | 79  | 
| 118 | 80  | 
| 119 | 80  |

**Comment by aanoaa** [comment]
| 허리  | 밑단   | 
|-----|------| 
| 78  | 7    | 
| 79  | 7    | 
| 80  | 7    | 
| 81  | 7    | 
| 82  | 7.25 | 
| 83  | 7.25 | 
| 84  | 7.25 | 
| 85  | 7.25 | 
| 86  | 7.25 | 
| 87  | 7.25 | 
| 88  | 7.5  | 
| 89  | 7.5  | 
| 90  | 7.5  | 
| 91  | 7.5  | 
| 92  | 7.5  | 
| 93  | 7.5  | 
| 94  | 7.5  | 
| 95  | 7.5  | 
| 96  | 7.75 | 
| 97  | 7.75 | 
| 98  | 7.75 | 
| 99  | 7.75 | 
| 100 | 7.75 | 
| 101 | 7.75 | 
| 102 | 8    | 
| 103 | 8    | 
| 104 | 8    | 
| 105 | 8    | 
| 106 | 8    | 
| 107 | 8    | 
| 108 | 8.25 | 
| 109 | 8.25 | 
| 110 | 8.25 | 
| 111 | 8.25 | 
| 112 | 8.25 | 
| 113 | 8.25 | 
| 114 | 8.5  | 
| 115 | 8.5  | 
| 116 | 8.5  | 
| 117 | 8.5  | 
| 118 | 8.5  | 
| 119 | 8.5  |

**Comment by aanoaa** [comment]
엉덩이,허리
82,59
83,59
84,60
85,62
86,64
87,65
88,66
89,67
90,68
91,69
92,70
93,71
94,72
95,73
96,74
97,75
98,76
99,77
100,78
101,79
102,80
103,82
104,84
105,85
106,86
107,87
108,88
109,89
110,90
111,91
112,92
113,93
114,94
115,95

**Comment by aanoaa** [comment]
| 엉덩이 | 길이 | 
|-----|----| 
| 82  | 46 | 
| 83  | 46 | 
| 84  | 46 | 
| 85  | 47 | 
| 86  | 48 | 
| 87  | 48 | 
| 88  | 48 | 
| 89  | 50 | 
| 90  | 51 | 
| 91  | 51 | 
| 92  | 51 | 
| 93  | 51 | 
| 94  | 51 | 
| 95  | 51 | 
| 96  | 52 | 
| 97  | 52 | 
| 98  | 52 | 
| 99  | 52 | 
| 100 | 52 | 
| 101 | 52 | 
| 102 | 52 | 
| 103 | 52 | 
| 104 | 53 | 
| 105 | 53 | 
| 106 | 53 | 
| 107 | 53 | 
| 108 | 53 | 
| 109 | 53 | 
| 110 | 53 | 
| 111 | 53 | 
| 112 | 53 | 
| 113 | 53 | 
| 114 | 53 | 
| 115 | 54 |

**Comment by aanoaa** [comment]
| 윗배  | 팔길이 | 
|-----|-----| 
| 50  | 56  | 
| 51  | 56  | 
| 52  | 56  | 
| 53  | 56  | 
| 54  | 56  | 
| 55  | 56  | 
| 56  | 56  | 
| 57  | 56  | 
| 58  | 56  | 
| 59  | 56  | 
| 60  | 56  | 
| 61  | 56  | 
| 62  | 56  | 
| 63  | 56  | 
| 64  | 56  | 
| 65  | 56  | 
| 66  | 56  | 
| 67  | 56  | 
| 68  | 56  | 
| 69  | 58  | 
| 70  | 58  | 
| 71  | 58  | 
| 72  | 58  | 
| 73  | 58  | 
| 74  | 58  | 
| 75  | 58  | 
| 76  | 58  | 
| 77  | 58  | 
| 78  | 58  | 
| 79  | 58  | 
| 80  | 58  | 
| 81  | 58  | 
| 82  | 58  | 
| 83  | 58  | 
| 84  | 58  | 
| 85  | 58  | 
| 86  | 58  | 
| 87  | 58  | 
| 88  | 58  | 
| 89  | 58  | 
| 90  | 58  | 
| 91  | 58  | 
| 92  | 58  | 
| 93  | 58  | 
| 94  | 58  | 
| 95  | 58  | 
| 96  | 58  | 
| 97  | 58  | 
| 98  | 58  | 
| 99  | 58  | 
| 100 | 58  |

**Comment by aanoaa** [comment]
| 길이 | 팔길이 | 
|----|-----| 
| 60 | 50  | 
| 61 | 50  | 
| 62 | 51  | 
| 63 | 51  | 
| 64 | 52  | 
| 65 | 52  | 
| 66 | 53  | 
| 67 | 53  | 
| 68 | 54  | 
| 69 | 55  | 
| 70 | 56  | 
| 71 | 57  | 
| 72 | 58  | 
| 73 | 59  | 
| 74 | 60  | 
| 75 | 60  | 
| 76 | 61  | 
| 77 | 61  | 
| 78 | 62  | 
| 79 | 63  | 
| 80 | 64  | 
| 81 | 65  | 
| 82 | 66  | 
| 83 | 66  | 
| 84 | 67  | 
| 85 | 67  | 
| 86 | 68  | 
| 87 | 68  | 
| 88 | 69  | 
| 89 | 69  | 
| 90 | 70  |

**Comment by yongbin** [comment]
참고로 노파심에서 말씀드립니다. #607 에서도 의류의 재고 파악을 단품기준으로 진행했다가 세트기준으로 변경했습니다. 아마 수선도 열린옷장에서 원하는건 단품수선과 세트수선을 나누는것일수 있으니 아직 논의가 안되셨으면 @10001if 님께 확인해보시는게 좋을거 같습니다.

**Comment by aanoaa** [comment]
어떠한 걱정인지는 알겠는데, 여기에는 해당사항이 없습니다.

**Comment by aanoaa** [comment]
요런식으로 csv 파일을 만듭니다.

``` perl
use utf8;
use strict;
use warnings;

use OpenCloset::Clothes qw( %WAIST_THIGH_MAP %WAIST_CUFF_MAP %HIP_WAIST_MAP %HIP_LENGTH_MAP %TOPBELLY_ARM_MAP %LENGTH_ARM_MAP );

binmode STDOUT, ':utf8';

print "길이,팔길이\n";
for my $key ( sort { $a <=> $b } keys %LENGTH_ARM_MAP ) {
    my $value = $LENGTH_ARM_MAP{$key};
    print "$key,$value\n";
}
```

**Comment by aanoaa** [comment]
> 의류가 특정상태가 아닐때(대여중 이라거나..) 수선장소가 입력되면 의류의
> 상태를 수선 으로 변경

- 대여가능
- 예약
- 세탁
- 수선
- 반납

인 의류에 대해서만 수선으로 변경하도록 하겠습니다.

**Comment by aanoaa** [comment]
하의를 중심으로 셋트의류 및 셋트의류가 아닌 하의 수선에 대한 과정은
해결되었습니다.

*셋트의류가 아닌 상의에 대한 수선*

역시 같은 방식으로 처리 되어야 합니다.

전혀 생각해보지 못했습니다.
어떻게 처리할지 고민해봐야 합니다.

**Comment by aanoaa** [comment]
배포전 주의사항만 지키면 됩니다.
https://github.com/opencloset/donation/pull/38#issuecomment-218527756
