### ISSUE TITLE
새로운 신청서가 들어오면 이메일로 알림

### ISSUE THREAD

**Issue by aanoaa** [opencloset/donation#4]
전체 메일로 알람이 올 수 있도록 해야 합니다.
메일서버를 구축하던지 있는 걸 활용하던지..

**Comment by aanoaa** [comment]
@yongbin 이거 SMTP host 를 localhost 로 해서 보내면 될까여

지난번에 volunteer 할때 메일서버 작업해주셨거든요.

https://github.com/opencloset/volunteer/issues/37

**Comment by yongbin** [comment]
넵 `opencloset1` 장비라면 기존 세팅이 그대로 적용되기 때문에 그냥 사용하시면 됩니다. 아래명령으로 방금 테스트해봤는데 잘 오는거 확인했습니다.

```sh
echo "Test" | mail yongbin.yu@gmail.com
```

**Comment by aanoaa** [comment]
옵니다

**Comment by yongbin** [comment]
메일이 메일서버까지는 정상적으로 전달되지만 스팸으로 분류되고 있습니다. 이를 완화하기 위해서는 SPF레코드를 등록하는 방법이 있습니다. 기존 `theopencloset.net`의 SPF 레코드는 아래와 같습니다.
```
v=spf1 a mx include:aspmx.googlemail.com include:_spf.google.com ~all
```

변경된 레코드는 아래와 같습니다.

```
v=spf1 a mx include:aspmx.googlemail.com include:_spf.google.com ip4:61.100.184.211 ~all
```

**Comment by yongbin** [comment]
SPF 레코드가 원인은 아니었지만 결과적으로는 SPF 레코드추가후 원활하게 메일을 잘 확인할 수 있습니다.

**Comment by aanoaa** [comment]
구글이 잘못했지만 내쪽에서 수정하였다
