### ISSUE TITLE
특정일 이후에 실제로 기증하신 분들의 연락처

### ISSUE THREAD

**Issue by aanoaa** [opencloset/donation#40]
안내등에 사용될 목적으로 어느 기간동안에 실제로 기증하신 분들의 연락처를 뽑아야 합니다.

**Comment by aanoaa** [comment]
2016-04-05 ~ 지금까지

에 대한 요청이 있습니다.

**Comment by aanoaa** [comment]
기증메세지가 입려된 날짜는 추적할 수 있지만,
언제 기증되었다를 기록하고 있지는 않습니다.

조건에 만족하는 대상을 뽑아야 하는데, 조건을 구체적으로 만들어야 합니다.

**Comment by aanoaa** [comment]
@yongbin 가능하시다면 DB 왕께서 해결해주세요.

**Comment by yongbin** [comment]
DB왕은 아니지만 제가 오늘중으로 처리하겠습니다

**Comment by yongbin** [comment]
아래  쿼리로 뽑았을때 83명이 나옵니다. 

```sql
SELECT
        a.`name`
        ,a.`email`
        ,c.`phone`
        ,b.`ddate`
FROM `user` AS a INNER JOIN (
                                SELECT      `user_id`
                                            ,MAX(`create_date`) AS ddate
                                FROM        `donation`
                                GROUP BY    `user_id`
                                HAVING      `ddate` >= '2016-04-05'
                                ORDER BY    `ddate` DESC ) AS b ON a.id = b.user_id
INNER JOIN `user_info` AS c ON a.`id` = c.`user_id`
```

@aanoaa `donation` 테이블에 기증메세지를 입력한시점을 기준으로 잡은건데 괜찮을까요? 문제없으면 이 목록을 엑셀로 @10001if 님께 보내겠습니다.

**Comment by aanoaa** [comment]
이 분들의 기증신청서 상태를 같이 확인해볼 수 있을까요?
`등록됨 registered` 이거나 `반송완료 returned` 이어야 하거든요.

신청서 없이 기증할 수 있기도 하지만 실수를 줄이는 차원에서 목록을 뽑고 @10001if 님이 눈으로
골라내야 하지 않을까 합니다.

**Comment by yongbin** [comment]
```sql
SELECT
        a.`name`
        ,a.`email`
        ,c.`phone`
        ,b.`ddate`
        ,d.`status`
FROM `user` AS a INNER JOIN (
                                SELECT      `user_id`
                                            ,MAX(`id`) AS did
                                            ,MAX(`create_date`) AS ddate
                                FROM        `donation`
                                GROUP BY    `user_id`
                                HAVING      `ddate` >= '2016-04-05'
                                ORDER BY    `ddate` DESC ) AS b ON a.id = b.user_id
INNER JOIN `user_info` AS c ON a.`id` = c.`user_id`
INNER JOIN `donation_form` AS d ON d.`donation_id` = b.`did`
WHERE d.`status` IN ('registered', 'returned')
```

상태를 추가했습니다. 이렇게 하니까 42명으로 줄어듭니다.

**Comment by aanoaa** [comment]
네 감사합니다.
두개의 목록 모두 @10001if 님의 이메일로 보내주세요.
@10001if 님은 목록을 직접확인하셔서, 어떤 것을 쓰실건지 남겨주세요.

**Comment by yongbin** [comment]
@10001if 님께 메일보냈습니다. @10001if  확인후에 이슈 닫아주세요.

**Comment by 10001if** [comment]
@yongbin 네 감사합니다. 확인하였습니다. 이슈 닫도록 하겠습니다.

**Comment by aanoaa** [comment]
@10001if 어떤 목록을 사용하는게 맞나요?

1. 기증메세지를 입력한날이 2016-04-05 ~ 오늘까지
2. 기증메세지를 입력한날이 2016-04-05 ~ 오늘까지이고, 기증신청서가 `등록됨` 혹은 `배송완료` 인 것

둘다 잘못되었을 수 있습니다.
기증메세지입력이 언제 이루어지고 있는지 모릅니다.

**Comment by aanoaa** [comment]
새로운 기증등록 절차로 바뀌면서부터, 
기증메세지를 입력한날을 기증한날로 여기고 있습니다.

이것이 해결할 수 없는 문제가 있는데, 지난날의 기증을 등록할 수 없다는
것입니다.

이 문제를 해결해야 합니다.

옵션정도로 여겨서 기본은 입력일을 기증한날로 하고, 특정일을 지정할 수
있도록 해야 합니다.


해서,

> 기증메세지를 입력한날이 2016-04-05 ~ 오늘까지이고, 기증신청서가
> 등록됨 혹은 배송완료 인 것

이게 맞습니다.

정확하게는 기증일을 입력할 수 있게 된다면, 위 내용이 맞습니다.
