### ISSUE TITLE
허리늘임이 가능한 의류의 수선이 제안된 차이를 나타냄

### ISSUE THREAD

**Issue by aanoaa** [opencloset/donation#42]
![screenshot-donation theopencloset net 2016-05-13 16-48-59](https://cloud.githubusercontent.com/assets/170528/15241431/d4aaa87a-192a-11e6-9ab7-f9e4f66778f3.png)

의 그림으로 예를 들면

    윗배 - 허리 - 허리늘임가능: 12cm

**Comment by 10001if** [comment]
@aanoaa 이거 부탁드리려고 이슈 쓰려고 했는데 여기 올라와 있었네요~

**Comment by 10001if** [comment]
![2016-07-19 4 46 01](https://cloud.githubusercontent.com/assets/4696328/16942392/c424c654-4dd0-11e6-8211-cca80dde711a.png)
이런식으로 부탁드리려고 했습니다~

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/913

**Comment by aanoaa** [comment]
계산된 값을 원하시는건데,
명확한걸로 보자면 지금이 더 좋지 않나 싶습니다.

`윗배둘레 - 허리둘레` 는 `9cm` 정도가 적당한데

    윗배 - 허리: 4cm

라고 하면 오히려 더 헛갈리지 않나요?
위 사진은 윗배 - 허리가 8cm 라서 허리늘임이 가능하더라도 허리를 늘이지 않습니다.

그래서 수선되는 항목은 허벅지와, 밑단 뿐 입니다.

**Comment by 10001if** [comment]
@aanoaa 말씀해주신 내용 정확하게 이해했습니다. 불필요한 정보가 추가될 뻔 했네요. 이 이슈는 닫도록 하겠습니다.
