### ISSUE TITLE
수선의류목록 진행상태를 비어있음으로 바꾸어도 리셋이 되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#47]
![2016-05-27 10 34 31](https://cloud.githubusercontent.com/assets/4696328/15595099/1124f414-23f7-11e6-9f48-4b513689035f.png) 수선은 여러번 할 수 있기 때문에, 비어있음으로 누르면 다시 원상태로 복구되어 수선을 다시 할 수 있다고 이해하고 있었는데요. 이상의 그림처럼 진행상태를 `비어있음`으로 바꾸어도 리셋이 되지 않습니다. 확인 부탁드리겠습니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/834

**Comment by aanoaa** [comment]
원상복구라는게 뭔지 모르겠습니다.
기존의류의 사이즈를 뜻하는 건가요?

**Comment by 10001if** [comment]
`수선장소` `비용` `사유` `맡긴날` `수거일`이 비어있는 상태로 되는 것을 말합니다.

**Comment by aanoaa** [comment]
원상복구 되지 않았습니다.
`치수변경` 이거나 `수선완료` 일때에는 또다시 치수변경을 하지 못합니다.
진행상태를 `없음` 으로 변경하면 치수변경이 가능해집니다.

나머지는 진행상태와 관계없이 동일합니다.

**Comment by aanoaa** [comment]
기능에 대해 설명이 부족했었습니다.
지금은 이해하였고, 그에 맞게 사용한다고 했습니다.
