### ISSUE TITLE
수선장소를 입력하면, 대여불가 상태가 수선 으로 변경될 수 있도록 요청

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#48]
![2016-05-27 10 35 35](https://cloud.githubusercontent.com/assets/4696328/15595178/b9a50926-23f7-11e6-991b-ceaf4cda37ee.png)
기존 항목 외에 대여불가 항목도 변경 될 수 있도록 요청드립니다. 확인을 해보니 동복, 하복 등이 계절에 맞지 않게 대여될 여지가 있어 대여불가 상태로 변경을 해놓고 사용하고 있었다고 합니다. 

최근에 하복을 수선하는 이유가 많아지다 보니 대여불가 항목도 변경이 될 수 있게 해달라는 요청이 많았습니다. ^^

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/835

**Comment by aanoaa** [comment]
![screenshot-localhost 5000 2016-05-27 11-47-57](https://cloud.githubusercontent.com/assets/170528/15596261/fc49806e-2400-11e6-97a8-216027ebee23.png)
