### ISSUE TITLE
팔길이 "0"으로 입력이 가능하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#49]
현재는 새옷등록 시 "0"으로 입력이 되지 않습니다. 
민소매 블라우스의 경우 `비어있음`이 아니라 `0`이 되는 것이 맞는 것으로 보입니다.
때문에 현재는 의류정보에 들어가 다시 수정하고 있습니다.

새옷 등록시 블라우스, 원피스의 경우 `0`사이즈도 입력이 가능하도록 수정 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/868

**Comment by aanoaa** [comment]
입력하지 않았을때는 `비어있음` 으로 하고 `0`을 입력했을때 `0`이 되도록 하겠습니다.
