### ISSUE TITLE
새옷등록할때에 태그도 함께 등록할 수 있도록

### ISSUE THREAD

**Issue by aanoaa** [opencloset/donation#52]
의류코드 밑에 여러개의 태그를 입력할 수 있도록..

**Comment by aanoaa** [comment]
![screenshot-donation theopencloset net 2016-10-24 19-09-06](https://cloud.githubusercontent.com/assets/170528/19641812/64ac1f6c-9a1d-11e6-852f-391a8f47b5cc.png)

공백 ` ` 혹은 쉼표 `,` 로 여러개의 태그를 입력할 수 있습니다.
태그가 없으면 만들어집니다.

    태그1 태그2 태그3

이렇게 입력해도 되고,

    태그1, 태그2, 태그3

이런식으로 입력해도 됩니다.

**Comment by 10001if** [comment]
@aanoaa 태그 등록할 수 있는 기능이 생겨서 참 좋은데요. 추가 요청사항이 있습니다. 직접 입력하는 방식을 사용하면 태그입력시 실수가 빈번하게 발생할 듯 합니다.
![2016-10-25 11 30 05](https://cloud.githubusercontent.com/assets/4696328/19671024/cfdaf838-9aa6-11e6-8aa4-7df67c86f12a.png) 
기존에 의류정보에서 입력하는 것과 같은 방식으로 태그를 입력하게 할 수는 없을까요? 직접 입력방식이 아니라 정해진 태그를 클릭하여 입력하는 방식으로 변경요청드리고자 합니다.

**Comment by aanoaa** [comment]
@10001if 변경되었습니다.
