### ISSUE TITLE
새옷등록

### ISSUE THREAD

**Issue by aanoaa** [opencloset/donation#6]
기존의 새옷등록은 기증과 관련된 지금의 요구사항을 모두 해결해 줄 수 없습니다.
이에 레거시를 내비두고 새로운 새옷등록 채널을 만들도록 합니다.

**Comment by yongbin** [comment]
새옷등록을 `donation` 하부에다 만드실예정이신가요??

**Comment by aanoaa** [comment]
네 기증된 의류를 새옷등록까지 연결시키려고요.

**Comment by yongbin** [comment]
기증받지 않은경우에도 새옷등록을 하는경우가 있으니까 새옷등록도 분리하는게 좋지 않을까요?

**Comment by aanoaa** [comment]
기증받지 않은경우에는 "열린옷장" 으로 등록하고 있지 않나요?
`새옷등록` 이라는 기능이 `기증`관 관련된 곳에 있는 것이 불편하신 건가요?

**Comment by 10001if** [comment]
온라인으로 넘어가기 전에 기증 프로세스를 완료하거 진행이 되어야 할 것 같습니다. 저도 구체적으로 구상된 내용이 부족하네요. 고민하면서 자주 찾아뵙도록 하겠습니다~!

**Comment by aanoaa** [comment]
> 기증받지 않은경우에도 새옷등록을 하는경우가 있으니까 새옷등록도 분리하는게 좋지 않을까요?

donation.theopencloset.net 에서 새옷등록을 하지 말자는 의견인데 제가 짬시켰습니다.
원안대로 진행합니다.

**Comment by 10001if** [comment]
옷캔이나 비백으로 가는 의류의 경우에는 처음부터 새옷등록을 하지 않고 그냥 택배에 담아 보내버립니다.
이렇게 되면 실제로 몇 벌이 기증되었는지 확인이 되지 않고, 기증자가 의류의 출처를 물었을 때도 답변을 하기가 어렵습니다. 기증으로 운영되는 단체이기 때문에 전체 기증된 의류를 모두 등록하고 등록 이후에 사용할 의류가 아니라면 폐기절차를 거쳐 다른 단체로 이동되는 기록을 남기고 싶습니다. 그리고 이와 함께 열린옷장에서 사용되는 의류 수량과 아닌 의류 수량을 체크하여 기증자가 기증시 최초 1회에는 기증 결과를 자동으로 안내토록 하였으면 좋겠습니다.

**Comment by 10001if** [comment]
즉, 기증된 모든 의류를 코드를 만들어 새옷 등록을 할 수 있도록 프로세스를 변경하였으면 합니다. 다만, 지금처럼 실제 바코드를 만들어 의류에 붙이는 방식은 일이 커지고 내용이 복잡해지기 때문에 사용할 의류는 기존처럼 실제 바코드를 등록하되, 사용하지 않을 의류(비백, 옷캔으로 가는 의류)는 가상의 바코드를 부여한 뒤 새 옷 등록을 하고 바로 폐기되어 재기증 되도록 하는 절차로 진행하고 싶습니다.

**Comment by aanoaa** [comment]
> 그리고 이와 함께 열린옷장에서 사용되는 의류 수량과 아닌 의류 수량을 체크하여 기증자가 기증시 최초 1회에는 기증 결과를 자동으로 안내토록 하였으면 좋겠습니다.

이거는 무슨 말인지 모르겠습니다.

**Comment by aanoaa** [comment]
- 지금보다 쉽게 폐기의류를 등록

하는게 새로운 `새옷등록` 에서의 할 일이 아닌가 싶습니다.

----------------------------------------------

자켓3벌, 바지3벌을 기증 받았다고 가정하겠습니다.

그중 1벌은 사용할 수 있고, 2벌은 다른 곳으로 보내집니다.

- 사용가능한 자켓, 바지에 사용될 바코드를 입력합니다.
- 나머지는 `폐기` 의류로 카테고리만 등록

이렇게 된다면 staff 는 사용할 의류의 사이즈 및 바코드를 입력하고,
사용하지 않을 의류는 카테고리만 입력합니다.

**Comment by aanoaa** [comment]
신청한 의류와 등록된 의류에 대한 정보를 새옷등록 할때에 알 수 있으면 도움이 될 것 같습니다.

    신청한 의류 2벌
    등록된 의류 1벌

이렇게 표시된다면 아직 잊고 등록하지 못한 의류를 파악하기 쉬울 것 같습니다.

**Comment by aanoaa** [comment]
> 그리고 이와 함께 열린옷장에서 사용되는 의류 수량과 아닌 의류 수량을 체크하여 기증자가 기증시 최초 1회에는 기증 결과를 자동으로 안내토록 하였으면 좋겠습니다.

새옷등록 결과를 기증자에게 SMS 로 알리는 내용인데, 아직 어떻게 할지 모르겠다고 합니다.
짬시키겠습니다.

**Comment by aanoaa** [comment]
현재 사용하고 있는 바코드 프린터기 입니다.
http://bixolon.com/html/en/product/product_detail.xhtml?prod_id=45&large_cd=0005

새옷등록과 바코드와 밀접한 관련이 있습니다.
지금 느끼는 불편함이 바코드와 사이즈 입력때문입니다.

**Comment by aanoaa** [comment]
- 새옷등록을 했다고 해서 대여가능 한것이 아니기 때문에 (수선을
  해야함?) 대여가능할때까지의 상태관리
- 입력된 사이즈에 따라서 수선에 관한 치수를 계산해서 제시함

**Comment by aanoaa** [comment]
@10001if 새옷등록에 관한 가이드 문서를 작성해야 합니다.

**Comment by aanoaa** [comment]
의류마다 의류텍을 프린트 할 수 있어야 합니다.

**Comment by aanoaa** [comment]
@10001if 적당한 크기의 용지 프린터기가 필요합니다.

**Comment by aanoaa** [comment]
의류에서 인쇄하면 현재 사용되는 의류텍과 비슷한 형식으로 출력되면 좋을 것 같습니다.

**Comment by aanoaa** [comment]
의류의 종류가 무엇이 되었든 폐기될 의류에 한해서 자동으로 바코드를 발급하려고 합니다.
last code 를 항상 별도의 파일에서 갱신하고 있는데, 이를 시스템에 등록하면 안되는 이유가 있나요?

------------------------

바코드와 관련된 내용

https://github.com/opencloset/opencloset/issues/39
https://github.com/opencloset/opencloset/wiki/barcode

**Comment by aanoaa** [comment]
의류 카테고리별로 last code 를 DB 에서 역추적 할 수 있는지 확인해봐야 합니다.

**Comment by yongbin** [comment]
> 의류의 종류가 무엇이 되었든 폐기될 의류에 한해서 자동으로 바코드를 발급하려고 합니다.
> last code 를 항상 별도의 파일에서 갱신하고 있는데, 이를 시스템에 등록하면 안되는 이유가 있나요?

아니요 시스템에 등록되면 더 좋습니다. 기존시스템에서는 바코드의 생성과 관련된 부분을 고려안했었기 때문에 별도에 스크립트에 lastcode를 관리했습니다. 만약에 생성부분이 자동으로 관리된다면 더 편할것같고 열린옷장에서도 예전에 요청이 있었습니다.

https://github.com/opencloset/opencloset/issues/550


> 의류 카테고리별로 last code 를 DB 에서 역추적 할 수 있는지 확인해봐야 합니다.

시도해본적이 있는데 불가능합니다. 왜냐하면 DB에 등록된 카테고리별 last code는 `사용된` 마지막 코드이지 `발행된` 마지막 코드가 아니기 때문입니다.

**Comment by aanoaa** [comment]
발행된 바코드: 인쇄를 위해 생성된 순차적인 코드
사용된 바코드: 인쇄된 바코드가 의류에 부착된후 새옷등록까지 마친 코드

바코드가 사용직전에 발행되지 않는다면 폐기될 의류의 바코드 자동등록은
어렵습니다.

시스템에서 폐기처리를 위해 발행된 의류의 바코드를 다른 사용가능 의류에
쓰일 수도 있기 때문입니다.

하지만 폐기될 의류의 바코드 앞자리를 따로 둔다면 가능하기도 합니다.
자켓은 `J` 로 시작하지만 폐기될 의류의 자켓은 `J` 일 필요가 없습니다.
사용되지 않는 알파벳으로 쓰는 겁니다. `X001` 처럼..

**Comment by aanoaa** [comment]
기증신청서 -> 기증행위 -> 새옷등록

으로 생각했었는데, 기증신청없이 새옷등록하는 절차 또한 필요할 것
같습니다.

열린옷장에서 옷을 샀다면?
이를 기증신청서를 작성하진 않을테고, 기증행위로는 등록하겠죠?

**Comment by aanoaa** [comment]
하나의 기증신청서에 의류를 나눠서 여러번의 기증행위로도 등록할 수
있어야 할까요?

**Comment by aanoaa** [comment]
일반적인 새옷등록의 가상의 시나리오

- 홍길동씨가 기증신청서를 작성하고 옷을 전달
- 홍길동씨의 신청서를 통해 홍길동씨의 기증A 를 추가(날짜별? 신청서별?)
- 홍길동씨의 기증A 에 대해 의류 1, 2, 3 을 폐기
- 홍길동씨의 기증A 에 대해 의류 4, 5, 6 을 등록

------------------------------------

- 열린옷장에서 의류를 구입
- 열린옷장의 기증A 를 추가
- 열린옷장의 기증A 에 대해 구입한 의류 1, 2, 3, 4, 5 를 등록

------------------------------------

- 고길동씨(둘리 아빠)가 기증신청서 없이 옷을 전달
- 고길동씨에 대해 기증자등록
- 고길동씨의 신청서를 통해 고길동씨의 기증A 를 추가
- 고길동씨의 기증A 에 대해 의류 1, 2, 3 을 등록

------------------------------------

- 홍길동씨가 기증신청서를 작성하고 옷을 전달
- 홍길동씨의 신청서를 통해 홍길동씨의 기증B 와 기증C 를 추가
- 홍길동씨의 기증B 에 대해 의류 1, 2, 3 을 등록
- 홍길동씨의 기증C 에 대해 의류 4, 5, 6 을 등록

**Comment by aanoaa** [comment]
새옷등록은 사용자의 기증행위에 대해 의류를 추가하는 작업입니다.

신청서가 있다면 신청서의 정보를 토대로 사용자를 등록/검색 할 수
있으니 문제 없습니다.

신청서가 없다면 사용자 검색을 통해 사용자를 선택할 수 있어야 합니다.

사용자를 검색했는데 없다면?
없으면 새로운 사용자를 등록후에 기증을 등록해야 합니다.
하지만 사용자가 등록되는 채널이 늘어나기를 원치 않습니다. 사용자
등록의 인터페이스만 두고 재고관리 서비스의 api 를 통해 사용자등록이
된다면 좋겠습니다.

**Comment by aanoaa** [comment]
새옷등록을 위해서는

- 사용자를 검색
- 사용자를 추가
- 사용자의 기증행위를 추가

할 수 있는 기능이 우선시되어야 합니다.
근데 지금 그게 없죠?(있긴한데 재고관리쪽에 있음)

그거 먼저 작업되어야 합니다.

사용가가 없을때 재고관리로 가서 사용자 추가하고 다시 이쪽으로 와서
등록 하는 작업을 하면 되지만 많이 번거로울 것 같습니다.

**Comment by 10001if** [comment]
> 홍길동씨가 기증신청서를 작성하고 옷을 전달
> 홍길동씨의 신청서를 통해 홍길동씨의 기증B 와 기증C 를 추가
> 홍길동씨의 기증B 에 대해 의류 1, 2, 3 을 등록
> 홍길동씨의 기증C 에 대해 의류 4, 5, 6 을 등록

하나의 신청서에는 하나의 기증행위면 충분해 보입니다.
따라서 기증B만 존재하면 될 것으로 생각됩니다.

**Comment by aanoaa** [comment]
새로운 사용자 등록은 재고관리에서 하고 여기서는 검색만 되는걸로 하겠습니다.

**Comment by aanoaa** [comment]
스키마는 준비되었지만 완료전에 변경될 수 있기 때문에 이번 이슈가 배포될때 스키마도 함께 배포하도록 하겠습니다.

**Comment by aanoaa** [comment]
새옷등록 절차가 끝난 후에 신청서에 대해서 상태를 변경할 수 있는 step 을 두었으면 합니다.

등록완료인 신청서에 대해 새로운 기증으로 등록하고, 여기에 옷들을 등록한후에 상태를 `등록됨` 으로 변경할건지 물어보는 과정이 있다면 좀 아름답지 않나..

**Comment by aanoaa** [comment]
새옷을 시스템에 등록하는 방법으론 두가지가 있습니다.

1. 기존 재고관리 시스템의 api 를 활용한다.
2. 새로 만든다.

새옷등록의 절차가 완전히 기부쪽에서 활용될 것이라면 새로 만드는 것이 좋을 것 같고,
재고관리 시스템을 레거시로 두고 계속 활용될 것 같으면 재활용 하는게 좋을 것 같습니다.

**Comment by aanoaa** [comment]
별 생각 없이 결정한건데, 새로 만들겠습니다.
새옷등록에 관련된 모든 작업이 앞으로 기부쪽에서 이루어질 것 같거든요.

**Comment by aanoaa** [comment]
의류의 카테고리별 마지막 코드가 [wiki](https://github.com/opencloset/opencloset/wiki/barcode) 에서 관리되고 있는데, 이를 시스템에서 관리되도록 하면 `X` 로 시작하지 않고도 폐기될 의류의 바코드를 생성해 낼 수 있습니다.

**Comment by aanoaa** [comment]
`clothes_code` 를 만들고 아래처럼 저장해두면 어떨까 합니다.

    | category | code |
    |-----------------|
    |  jacket  | J200 |
    |  pants   | P150 |
    |  ...     | ...  |

**Comment by aanoaa** [comment]
폐기되는 의류에 대해서 2차 상태가 필요합니다.
폐기후에 옷캔으로 가는지,
폐기후에 진짜로 폐기되는건지 등에 대한 파악이 필요합니다.

**Comment by aanoaa** [comment]
상태를 추가해서 해결할 수 있을 것 같습니다.

`폐기` 뿐만 아니라, `폐기(옷캔)`, `폐기(비백)` 등으로 늘려나가면 되지 않을까 합니다.

**Comment by aanoaa** [comment]
@10001if 수량을 파악해야 하는 폐기종류에 대해 알려주세요.

옷캔, 비백(?) 말고 다른 것도 있나요?

**Comment by aanoaa** [comment]
#### 의류코드와 상태

의류는 사용되다가 찢어지거나 망가져서 폐기될 수 있습니다.
처음부터 망가진 옷이라서 폐기로 등록될 수도 있습니다.

의류의 마지막코드를 시스템에서 관리하면서
이런의류를 구분이 가능하다면, 폐기코드 뿐만 아니라 사용될 다음 코드 또한 예측할 수 있습니다.

현재 `폐기`를 위해 사용되는 상태코드는 하나입니다.

폐기를 위해 자동발급 되는 의류코드는 이미 발행된 바코드보다 높습니다.
폐기가 아닌 의류는 등록될때 발행된 바코드중에 하나를 골라서 등록하게 됩니다.

- 의류코드가 자동으로 발급된 폐기의류
- 사용되다가 폐기되는 의류

를 구분가능하도록 상태설정을 한다면 현재 마지막에 등록된 카테고리별 의류코드를 알아낼 수 있습니다.

    SELECT code FROM clothes WHERE category = 'jacket' AND status_id NOT IN (x, x, x) ORDER BY id DESC LIMIT 1;

**Comment by aanoaa** [comment]
- `폐기(옷캔)`
- `폐기(비백)`
- `폐기(레알)`

상태를 추가하게 된다면,

`폐기` 상태는 등록되어서 사용되다가 폐기를 의미하고,
`폐기(옷캔)`, `폐기(비백)`, `폐기(레알)` 상태인 의류는 모두 처음부터 폐기된 의류들입니다.


폐기될 의류의 코드는 last code 로 부터 만들어낼 수 있고,
사용될 의류의 코드는 위의 쿼리를 통해서 발행된 last code 를 알아낼 수 있고 이를 통해 추측해 낼 수 있습니다.

**Comment by aanoaa** [comment]
왜 이런이야기를 하는가하면, 의류를 등록할때에 종류별로 다음 바코드를 제안해줄 수 있습니다.
그럼 staff 는 발행된 바코드와 제안된 바코드를 비교해볼 수 있고 실수를 줄일 수 있지 않을까 합니다.

**Comment by aanoaa** [comment]
- 재활용(옷캔)
- 재활용(비백)
- 사용못함

정도의 상태를 추가하면 어떨까 합니다.

**Comment by aanoaa** [comment]
발행된 코드가 순서대로 사용되고 있지 않습니다.
이렇게 되면 의류코드의 제안은 어렵습니다.

**Comment by aanoaa** [comment]
@10001if 의류텍의 출력 예시를 만들어서 주세요

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/756

의 요구처럼 새옷등록에 대한 기능은 추가되었습니다.
의류텍의 프린트는 새로운 이슈(https://github.com/opencloset/opencloset/pull/778) 에서 진행됩니다.
