### ISSUE TITLE
반송완료 상태로 바로 바뀌면 sms가 발송되도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#61]
기증자분들이 sms 통하여 반송날짜를 신청하지 않고 전화를 통하여 반송신청을 하고 기증박스가 도착했을때, 기증신청서 상태를 바로 반송완료로 바꾸면 기증자분들에게 sms가 발송되지 않습니다. 

반송완료 상태로 바로 바뀌면 sms가 도착했다는 문자가 갈 수 있도록 수정 요청드립니다.

**Comment by 10001if** [comment]
![eec3b6ac7aa14134aaa535a139f474d4](https://cloud.githubusercontent.com/assets/4696328/21210268/f28e1ffc-c2bc-11e6-802e-9517becc94f8.jpg)

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1094

**Comment by aanoaa** [comment]
`배송완료 -> 반송완료` 일때에 문자가 보내져야 하는건가요?
맞다면 어떤 문자가 보내져야 하나요?

**Comment by aanoaa** [comment]
@10001if 이거 답변 좀 주세요.

**Comment by 10001if** [comment]
@aanoaa `반송신청`->`반송중`
`반송중`->`반송완료` 일때 문자가 발송되어야 하구요.
문자 내용은 기존 내용과 동일합니다~

**Comment by aanoaa** [comment]
@10001if `반송신청->반송중`, `반송중->반송완료` 일때는 이미 문자가 발송되고 있습니다.
문의해 주신 내용은 반송신청 절차를 무시하고 상태를 임의로 변경했을때 문자가 발송되어야 한다는 것 같습니다.

어떤상태에서 어떤상태로 변경되면 무슨내용의 문자메세지가 발송되어야 하는 건가요?

**Comment by 10001if** [comment]
`배송완료->반송완료` 일 경우 문자가 발송되어야 합니다.
그 내용은 '반송중->반송완료`에서 발송되는 내용과 동일합니다.
