### ISSUE TITLE
수선프로그램에서 자켓/바지가 아닌 다른 항목 코드를 입력가능하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#62]
수선프로그램에서 자켓/바지가 아닌 다른 항목 코드가 입력될 경우에 잘못된 요청(Not supported category)이라는 오류코드가 리턴됩니다. 자켓/바지 이외에도 봉제수선을 의뢰하는 경우가 있기 때문에 다 의류의 추가도 필요하다고 합니다. 대신 다른 의류들은 `기타`로 묶어 처리하여도 무방합니다. 
![2016-12-15 11 54 17](https://cloud.githubusercontent.com/assets/4696328/21210355/acf4678e-c2bd-11e6-917e-aef8f76a1937.png)

![18085365a8f4987ec21ccc83c7f03644](https://cloud.githubusercontent.com/assets/4696328/21210288/1ea47afa-c2bd-11e6-9018-e97ad03330ab.jpg)

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1095

**Comment by aanoaa** [comment]
검색했을때에만 보여지게 하면 될까요?
목록에 넥타이, 벨트등 수선제안이 필요치 않은 의류들이 보여지게 되면 관리가 어려울 수 있습니다.

**Comment by 10001if** [comment]
네! 검색했을때만 보여지도록 수정 요청드립니다.

**Comment by aanoaa** [comment]
@10001if 확인하셨다고 했는데 reopen 되었습니다.

**Comment by 10001if** [comment]
수선 프로그램에 B0J1를 입력할 경우 리스트에 바코드가 뜨지 않습니다. 다른 블라우스(B0BS)는 잘 나옵니다. 확인 부탁드립니다.
![2017-01-06 4 29 20](https://cloud.githubusercontent.com/assets/4696328/21710634/6824e8aa-d42d-11e6-9084-e6945fe3309e.png)

**Comment by 10001if** [comment]
@aanoaa 확인 시에는 잘 되었는데.. 이 블라우스만 그런건지 잘 모르겠네요. 우선 이슈에 올려놓습니다.

**Comment by aanoaa** [comment]
실수에 의한 버그입니다.
