### ISSUE TITLE
복수 의류 선택 후 일괄 태그 등록 및 삭제

### ISSUE THREAD

**Issue by aanoaa** [opencloset/donation#65]
https://github.com/opencloset/opencloset/issues/922

**Comment by aanoaa** [comment]
작업하면서 태그와 관련된 기능을 옮기고자 하는데(삭제 및 추가),
재고관리의 API 를 사용하기 보다는 똑같은 기능을 donation 에 넣는 것이 바람직 할까요?

cc @keedi @yongbin

**Comment by aanoaa** [comment]
일괄로 태그추가가 가능해야 하고 일괄로 상태변경도 가능해야 합니다.

**Comment by 10001if** [comment]
@aanoaa 태그 삭제, 추가, 상태변경 시에도 입력한 수량을 확인 할 수 있도록 넘버링 추가를 요청드립니다. ^^
![2017-01-06 6 04 33](https://cloud.githubusercontent.com/assets/4696328/21712943/aede261e-d43a-11e6-981d-84ac319780ab.png)

**Comment by aanoaa** [comment]
28730496272988ca5f43c6fb47e5240e157bf0b2
