### ISSUE TITLE
진행상태에서 초기화 상태를 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#69]
기존에 입력했던 내용을 지울 수 있는 기능이 필요하다고 합니다. 진행상태에서 `초기화` 상태를 추가해서 초기화가 될 수 있도록 하는 방법을 요청드립니다. ^^

**Comment by 10001if** [comment]
![2017-01-06 4 33 19](https://cloud.githubusercontent.com/assets/4696328/21710787/3f296ca4-d42e-11e6-9da1-27878c1ebb3e.png)

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1124

**Comment by aanoaa** [comment]
비어있는 곳을 클릭하면 되지 않나요?

**Comment by 10001if** [comment]
@aanoaa 저도 그렇게 된다고 생각했는데.. 안되더라구요..

**Comment by aanoaa** [comment]
제 PC 기준으로는 됩니다.

**Comment by 10001if** [comment]
@aanoaa 아.. 제가 이슈를 잘못 설명한 것 같습니다. 비어있는 곳을 클릭하면 `진행상태` `수선장소``비용``사유`	`맡긴날``수거일`이 모두 초기화 되는 것을 요청드린 것입니다.
