### ISSUE TITLE
기증 신청 페이지 푸터에 있는 전화번호의 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#75]
현재는 070-으로 되어 있습니다. 이 번호는 02-6929-1029로 변경 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1133

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Plugin-Helpers/issues/5 에서 처리하도록 하겠습니다.

**Comment by 10001if** [comment]
현재는 02-6929-1029로 되어 있습니다. 02-6929-1020 으로 변경 요청드립니다. 제가 번호를 착각했었네요 ^^;

**Comment by aanoaa** [comment]
아직 OpenCloset::Plugin::Helpers v0.0.13 을 배포하지는 않았습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Plugin-Helpers-v0.0.13.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Plugin-Helpers-v0.0.13.tar.gz) 배포하였습니다.
