### ISSUE TITLE
기증신청서 작성시 전화번호가 10자리일 경우 오류가 발생함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#76]
기증신청서 작성시 전화번호가 10자리일 경우에 ex)000-123-4567 기증신청서 작성을 완료하고 최종적으로 신청할 경우에 오류가 발생합니다. 수정 요청드립니다. ^^

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1136

**Comment by aanoaa** [comment]
전혀 고려하지 않았습니다.
아직도 10자리 전화번호가 사용되는 줄 몰랐습니다.

**Comment by 10001if** [comment]
@aanoaa 저도 생각하지 못했는데.. 사용하는 분이 있다고 하시네요 ^^;;

**Comment by aanoaa** [comment]
`010-123-4567` 번호라고 가정했을때 입력하면 아래처럼 될 것입니다.

![2017-01-12 15-26-38](https://cloud.githubusercontent.com/assets/170528/21879343/8d49277e-d8db-11e6-99ec-755b18cc5244.png)

**Comment by 10001if** [comment]
@aanoaa 네~ 알겠습니다. 감안해서 보겠습니다~

**Comment by aanoaa** [comment]
![bad request 2017-01-12 15-31-45](https://cloud.githubusercontent.com/assets/170528/21879452/497ff102-d8dc-11e6-92a0-20d359e7a8b6.png)

위와 같은 오류 화면이 나타납니다.
의도했던 정상적인 처리입니다.

이번에 해야할 작업은 10자리의 전화번호도 허용하는 것입니다.
