### ISSUE TITLE
확인요망 상태의 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#78]
`배송중` 상태에서 신청일자 기준으로 일주일이 넘도록 배송완료가 되지 않는 신청서의 경우 
`배송완료` 상태에서 신청일자 기준으로 일주일이 넘도록 반송신청이 되지 않는 신청서의 경우
`반송중` 상태에서 반송일자 기준으로 일주일이 넘도록 반송완료가 되지 않는 신청서의 경우에는

`재능나눔`처럼 `확인요망`의 상태를 추가하여 신청서를 보려고 합니다.

이상의 3가지 상태는 기증절차가 제대로 이뤄지고 있지 못함에도 불구하고 옷장지기가 인지하지 못하는 경우이기 때문입니다. 

확인요망도 `신청됨` `반송신청`과 마찬가지로 새로운 신청서가 들어오는 경우 별표를 통해 신규 신청서가 존재하는지 여부를 알아야 합니다.

또한 현재는 반송신청이 한번 입력되면 변경할 수 없습니다. 반송신청 이후에 여러가지 이유로 반송신청일을 바꿔야 하는 이슈가 있으므로 반송신청일 우측에 수선과 같이 리프레시 버튼![2017-01-18 6 21 06](https://cloud.githubusercontent.com/assets/4696328/22058233/96d0c598-ddab-11e6-89eb-8c2a476fa31f.png)을 달아 반송신청일을 초기화 하는 기능이 필요합니다. 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1145

**Comment by aanoaa** [comment]
> 배송완료 상태에서 신청일자 기준으로 일주일이 넘도록 반송신청이 되지 않는 신청서의 경우

현재는 2주이상 배송완료(delivered) 상태인 주문서를 반송안함(do-not-return) 으로 변경하고 있습니다.

- 이걸 1주일로 변경해야 하나요?
- 변경과 동시에 확인요망이어야 하나요?

> 배송중 상태에서 신청일자 기준으로 일주일이 넘도록 배송완료가 되지 않는 신청서의 경우
> 반송중 상태에서 반송일자 기준으로 일주일이 넘도록 반송완료가 되지 않는 신청서의 경우

문의해주신 내용은 상태를 두개 가지고 있어야 한다는 뜻 같습니다.

- 확인요망이면서 신청됨
- 확인요망이면서 반송신청

현재 **상태**는 주문서의 진행과정의 의미로 쓰이고 있습니다.
확인요망 상태 추가라기보다는 `email 의 별표기능처럼` 주문서에 체크해두고 따로 목록으로 보고 싶으신 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 이해하신 부분이 맞습니다.

제가 깜빡하고 있었는데.. 


> 현재는 2주이상 배송완료(delivered) 상태인 주문서를 반송안함(do-not-return) 으로 변경하고 있습니다.
> 
> 이걸 1주일로 변경해야 하나요?
> 변경과 동시에 확인요망이어야 하나요?

1주일로 변경해 주시구요. 변경과 동시에 확인요망으로 요청드립니다.

**Comment by 10001if** [comment]
확인요망 상태의 추가는 아니고 따로 주문서 목록을 보고 체크하려는 목적입니다.

**Comment by aanoaa** [comment]
- 신청서에 flag 를 두고 따로 모아보고 싶다
  - 체크해둔 신청서들을 볼 수 있는 목록이 필요
- 반송신청일을 수정하고 싶다

로 요약할 수 있겠습니다.

**Comment by aanoaa** [comment]
> 반송신청일을 수정하고 싶다

이거는 `/forms/:신청서번호/return?authorized=1` 로 들어가시면 가능합니다.

**Comment by aanoaa** [comment]
목록에서 보면 `반송신청` 링크가 있는데 거기에서 신청서번호만 스슥 바꾸면 됩니다.

**Comment by aanoaa** [comment]
위 링크를 통해서 반송일을 변경하면 상태가 `반송신청` 으로 변경됩니다.
원하는 기능이 아닙니다.

**Comment by 10001if** [comment]
@aanoaa 

> 신청서에 flag 를 두고 따로 모아보고 싶다
> 체크해둔 신청서들을 볼 수 있는 목록이 필요
> 반송신청일을 수정하고 싶다

정확히 이해해 주셨습니다. 본 기능이 필요합니다.

**Comment by pingpongworks** [comment]
현 시점에서 꼭 필요하지 않은 이슈라 닫겠습니다.
