### ISSUE TITLE
수정되어야 할 문구 내용입니다. 

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#8]
*
donation

1. 첫화면

- 첨부파일 참고

2. 그 외 기증방법 
i 직접 열린옷장에 방문하여 기증하셔도 됩니다.(을>에)

3. 기증품목 내용 수정

-여성용에 '원피스'품목을 추가해주세요

-
<문구수정>
누구나 멋질 권리가 있다!

열린옷장은 삶의 특별한 순간, 정장이 필요한 이들을 응원하기 위한 곳입니다.
입사면접, 졸업식, 결혼식, 사진촬영에 적합하다고 판단되는 옷을 보내주세요. 

아래 기증품목 상세 안내를 확인해주세요
(이거 아름다운 가게처럼 클릭하면 보이게 할 수는 없나요~?) 

4. 보내실 의류 종류에서
자켓(상의)
바지/치마(하의)

5. [의류 분류 절차 및 재기증 동의]
기증하신 의류가 열린옷장에서 사용되기에 적합하지 않은 경우 다음과 같이 사용될 수 있습니다.
(((((아래 내용은 같습니다~~))))))

6. [재능나눔 의사 확인]
열린옷장을 찾는 후배들에게 본인의 재능까지 나눌 의사가 있으십니까?

전문적인 분야의 재능도 좋고, 선배로서의 경험도 좋습니다. 재능나눔을 할 수 있는 자리가 마련된다면 참여할 의사가 있으신가요?
-
- 

재능나눔 의사가 있으시다면, 어떤 분야 혹은 어떤 회사에서 일하고 계신지 상세히 알려주세요. 

7. 신청완료 후 문구 

김민영 님, 기증신청이 정상적으로 접수되었습니다. 

기증신청 정보는 다음과 같습니다. 정확히 기입 되었나요?

성함
전화번호
주소
이메일

신청 정보에 오류가 있을 경우 이메일로 변경된 정보를 보내주시기 바랍니다. 
- 열린옷장 이메일 주소 : info@theopencloset.net

신청 정보에 이상이 없다면
주말을 제외한 2~3일 이내에 신청주소로 기증상자가 발송될 예정입니다.
조금만 기다려주세요. ^^

기증신청 진심으로 감사드립니다. 

* 
forms

1. 재기증을 동의하지 않거나/ 재능나눔에 동의하는 경우
색이나, 밑줄 생기게 만들어 주실 수 있나요? 

*
문자메시지

"토요일"은 기사님이 방문할 수 없으니 선택가능한 일자에서 제외시켜주세요~~

1

김민영 기증자님, 안녕하세요. 열린옷장입니다. 

의류를 보내실 수 있는 기증상자를 신청하신 주소로 발송하였습니다. 산간 도서 지방을 제외하고는 약 2~3일 내에 도착하리라 예상됩니다. (택배사 : CJ대한통운)

기증신청 다시 한 번 진심으로 감사합니다.

- 모두를 위한 공유 옷장, 열린옷장

2

김민영 기증자님, 안녕하세요. 열린옷장입니다.

보내드린 기증 상자 잘 받으셨나요? 열린옷장의 '참~ 쉬운' 기증 방법 안내해드리겠습니다. 

1. 기증상자에 의류를 담는다.
2. '나의 정장 기증이야기'를 작성한다.
3. 아래 링크로 기증상자를 수거해갈 날짜를 선택한다.
4. 해당 날짜에 방문한 cj 택배 기사님께 기증상자를 전달한다. 

보내주시는 기증의류와 기증이야기는 열린옷장을 찾는 많은 분들을 응원합니다.

- 모두를 위한 공유 옷장, 열린옷장

3
김민영 기증자님, 반송 신청 완료되었습니다. 신청하신대로 2월 27일 cj 택배 기사님이 방문하여 기증상자 수거 예정입니다.

택배사 사정에 따라 방문이 지연될 수 있습니다. 

- 모두를 위한 공유 옷장, 열린옷장

4
김민영 기증자님, 보내주신 기증상자 잘 도착했습니다. 감사합니다. 

빠른 시일 내에 검수 및 선별 작업이 이루어질 예정입니다. 꼼꼼하게 확인한 후에 선별 결과 및 기증 의류 사용처를 다시 한 번 안내해드리겠습니다. 

소중한 기증과 응원, 진심으로 감사드립니다.

- 모두를 위한 공유 옷장, 열린옷장

**Comment by 10001if** [comment]
@aanoaa 제가 다시 설명드리도록 하겠습니다.

**Comment by 10001if** [comment]
[수익나눔-프로세스.pptx](https://github.com/opencloset/donation/files/166388/-.pptx)

**Comment by aanoaa** [comment]
> 보내실 의류 종류에서
> 자켓(상의)
> 바지/치마(하의)

기증품목에서 `팬츠` 대신에 `바지/치마` 로 변경해야 합니다.

**Comment by aanoaa** [comment]
> [의류 분류 절차 및 재기증 동의]

    기증하신 정장이 열린옷장에서 사용되기에 부적합한 경우 다음과 같이 쓰이는 것에 동의하십니까?

의 제목입니다.

**Comment by aanoaa** [comment]
> [재능나눔 의사 확인]

     새로운 시작을 계획하며 열린옷장을 찾아오는 분들에게 본인이 가진 재능까지 나눌 의사가 있으십니까? 

의 제목입니다.

**Comment by aanoaa** [comment]
> 기증하신 정장이 열린옷장에서 사용되기에 부적합한 경우 다음과 같이 쓰이는 것에 동의하십니까? 

    s/정장이/의류가/

로 변경해야합니다.

**Comment by aanoaa** [comment]
그외 문자 메세지내용을 확인해서 바꾸어야 합니다.

**Comment by aanoaa** [comment]
https://donation.theopencloset.net/guide2 에서

> 열린옷장은 버려지는 의류를 재활용하는 곳이 아닙니다.
입사면접, 졸업식, 결혼식, 사진촬영 등 삶의 특별한 순간을 위해 정장이 필요한 이들을 응원하기 위한 곳입니다.
그래서 조금 깐깐하게 기증받습니다. 누군가의 멋진 모습을 위해 좋은 옷만 필요하기 때문입니다. 

문구수정

`기증품목 상세 안내` 를 클릭하면 볼 수 있도록

하는 작업을 해야합니다.
