### ISSUE TITLE
새 옷 등록시 특정 사이즈 항목의 경우 x2된 값이 등록될 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#80]
둘레의 경우에는 곱하기 2를 해야 하는데, 이거 하는게 생각보다 어렵다는 의견이 많네요.. 새옷 등록시 다음의 항목은 입력값의 x2가 등록될 수 있도록 수정 요청드립니다. 

- 자켓
  - 가슴/윗배/배꼽
- 팬츠
  - 허리/엉덩이/허벅지
- 스커트
  - 허리/엉덩이
- 셔츠
  - 가슴
- 블라우스
  - 가슴
- 원피스
  - 가슴/허리/엉덩이
- 코트
  - 가슴
- 조끼
  - 윗배

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1146

**Comment by aanoaa** [comment]
100 넣었으면 200 이 등록되어야 하는거죠?

입력값을 시스템이 수정하면 어 이거 왜이래? 하는 상황이 발생할 수 있습니다.
뭐 적절히 변환된다면 좋겠지만요.

제 아이디어는 `x2` 해주는 버튼이 있어서 모든 값을 입력하고 `x2` 버튼을 눌렀을때에 입력값이 변경되면
그걸 사람이 확인하고 등록하는 방법이 어떨까 합니다.

**Comment by aanoaa** [comment]
- 100 넣고
- `x2` 버튼 누르고
- 200 으로 변경된걸 확인하고
- 맞으면 등록 틀리면 수정

**Comment by 10001if** [comment]
@aanoaa 좋은 생각이세요! 저도 그냥 넣는건 좀 불안하다 싶었는데.. 좋은 방법입니다! ^^

**Comment by aanoaa** [comment]
의류의 종류와 상관없이 모든 둘레들은 x2 기능이 필요한게 아닐까 합니다.

- 가슴
- 윗배
- 배꼽
- 허리
- 엉덩이
- 허벅지
- 밑단
- 목

**Comment by 10001if** [comment]
@aanoaa 맞습니다. 의복 종류와 관계없이 둘레는 모두 x2 입니다.

**Comment by aanoaa** [comment]
![2017-02-28 09-28-42](https://cloud.githubusercontent.com/assets/170528/23386182/540c3bea-fd98-11e6-8cb7-21a9bac0c80d.png)

**Comment by 10001if** [comment]
둘레X2 적용된 것 사용해보았는데요. 아래 사항 수정 부탁드립니다. 
1. 밑단둘레는 제외해주세요.
2. 0.5 단위는 곱하기가 안되요. 
EX) 30.5 를 60이 됩니다. 61이 되게 해주세요.

**Comment by 10001if** [comment]
@aanoaa 요청받은 사항을 올렸습니다~

**Comment by aanoaa** [comment]
어디 둘레가 소숫점이 되나요?
밑단둘레는 소수점을 고려했지만 다른 곳은 그렇게 하지 않았습니다.

**Comment by 10001if** [comment]
다른 둘레 모두 입니다. x2를 한 값일 때에는 소수점이 문제가 되지 않았는데. 예를들어 가슴둘레 한면이 50.5cm일 경우 곱하면 101이 되어야 하는데, 현재는 100이 된다고 합니다.

**Comment by aanoaa** [comment]
```
neck            | int(11)
bust            | int(11)
waist           | int(11)
hip             | int(11)
topbelly        | int(11)
belly           | int(11)
arm             | int(11)
thigh           | int(11)
length          | int(11)
```

여지껏 밑단둘레를 제외한 다른 부분들은 모두 정수형을 사용하지 않았나요?
일단 소수점으로 저장할 수도 없습니다.

**Comment by aanoaa** [comment]
소숫점으로 입력한 값을 x2 해서 정수형으로 변환하도록 하겠습니다.
