### ISSUE TITLE
수선내역 삭제를 위해 초기화 버튼을 누른 뒤에도 수선 추천이 동작하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#84]
수선 프로그램에서 기존의 수선내역을 지우기 위해서 초기화 버튼을 눌렀을때, 수선추천 기능이 기존과 동일하게 동작하도록 수정 부탁드립니다. 한번 수선완료된 의류는 수선내역을 지워도 수선추천이 다시 동작되지 않는 것으로 확인됩니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1179

**Comment by aanoaa** [comment]
1. 치수 제안
2. 제안된 치수에 맞게 의류의 사이즈 변경(치수변경, 수선완료)
3. 다시 치수변경을 위해 상태를 변경
4. 치수 제안이 아니됨

-----------------------

이게 문제인 건가요?
제안된 치수에 맞게 의류의 사이즈가 변경되었다면 당연히 치수제안이 아니될 것 입니다.
(제안할게 없기 때문에)

**Comment by aanoaa** [comment]
제안이 안된 것이 아니라 제안 조건에 맞지 않았다고 볼 수 있습니다.

`윗배둘레 - 허리` 를 `A` 라고 하겠습니다.

- `A`가 0 보다 작다면 허벅지와 밑단을 수선
- `A`가 5 ~ 8 이라면 허벅지와 밑단을 수선
- `A`가 8 보다 크다면
  - 윗배 - 9 만큼 허리늘임이 가능하다면 허리, 허벅지, 밑단을 수선
  - 윗배 - 9 만큼 허리늘임이 가능하지 않다면 허리를 최대한 늘이고 허벅지, 밑단을 수선
- `A`가 5보다 작다면 허리, 허벅지, 밑단을 수선

이러한 조건들이 있습니다.

**Comment by pingpongworks** [comment]
수선 프로그램을 사용하고 있지 않아서 이슈 닫겠습니다.
