### ISSUE TITLE
옷 등록 시 검색을 통해 태그를 입력할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#86]
옷을 등록할 때 태그 수가 많아져서 태그를 찾기가 매우 어렵습니다. 검색을 통해 태그를 입력하는 기능의 추가를 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1185

**Comment by aanoaa** [comment]
이거 지금 이미 되고 있는 기능입니다.
확인해봐주세요.

**Comment by 10001if** [comment]
@aanoaa 첫단어로는 검색이 되는데, 중간 단어로는 검색이 되지 않습니다. 모든 단어가 검색 가능하도록 수정을 요청드립니다. 예) 지하_박스_하복 태그는 `박스`나 `하복`으로는 검색이 되지 않습니다. 지하로만 검색이 됩니다. 확인 부탁드릴게요.

**Comment by 10001if** [comment]
@aanoaa 중간 단어로 검색이 되긴 하나, 의류를 다 등록하고나면 검색해야할 창에 커서가 사라지는 현상이 있습니다. 확인 부탁드릴게요~

**Comment by aanoaa** [comment]
이해하지 못했습니다.

**Comment by 10001if** [comment]
@aanoaa 태그는 처음에 거는 경우보다는 의류의 사이즈와 색상 성별 등을 모두 입력하고 최종적으로 입력하는 경우가 일반적입니다. 그런데, 이렇게 정보들을 입력하고 나면 창에 커서를 넣을 수 없어 입력이 되지 않는 문제가 있습니다.

**Comment by 10001if** [comment]
![2017-03-08 11 37 17](https://cloud.githubusercontent.com/assets/4696328/23687817/ce56b842-03f3-11e7-938a-dbb39cdd2a59.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
오늘 확인해보니 의류의 종류(자켓, 블라우스..)를 누르면 태그에 커서가 입력되지 않는 현상이 있었습니다. 확인 부탁드릴게요. 파이어폭스에서 실행했는데 커서 입력이 되지 않았었습니다.

**Comment by aanoaa** [comment]
제 개발환경에서는 재현되지 않습니다.
새로고침해서 테스트해주시거나 직접 보여주세요.

**Comment by 10001if** [comment]
@aanoaa Ctrl+R 한 뒤 진행해보라고 했는데, 지금은 된다고 하네요. 오전에 직접 볼 때 안되던 이유가 이것 때문이었나 싶네요. 다음엔 좀 더 꼼꼼하게 확인해보겠습니다. ^^
