### ISSUE TITLE
수선프로그램에서 바로 사이즈를 수정할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#87]
의류정보에 들어가거나 전체변경을 통해 사이즈를 변경할 수 있습니다. 
하지만 사이즈 변경이 적은 경우나 임의로 사이즈를 변경하는 경우가 많아 직접 사이즈를 변경할 수 있도록 요청이 많이 드어왔습니다. 수선 프로그램에서 미리보기 한 경우 직접 사이즈 변경이 가능하도록 수정 요청드립니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1187

**Comment by aanoaa** [comment]
![2017-04-20 12-38-01](https://cloud.githubusercontent.com/assets/170528/25212595/369e8e40-25c6-11e7-9d09-88baa17a5126.png)

여기에서요?
팝업 같은걸 띄우길 원하시는 건가요?
재고관리 링크로 들어가서 수정하기가 불편한 건가요?

**Comment by aanoaa** [comment]
![2017-04-20 12-43-51](https://cloud.githubusercontent.com/assets/170528/25212724/115c6340-25c7-11e7-9ffa-21b7ff5942b0.png)

위 사진에서 허리둘레와 길이가 수선제안 되었지만, 실제로는 길이는 수선하지 않을때에 길이는 변경되지 않는 기능을 원하는 것 입니다.

**Comment by aanoaa** [comment]
![2017-04-20 14-35-50](https://cloud.githubusercontent.com/assets/170528/25215171/ae715c30-25d6-11e7-9b19-1b8a8be964b8.png)

수선가능한 부위(?)를 토글할 수 있도록 했습니다.
위 경우라면 허리와 허벅지는 `치수변경` 버튼을 눌러도 사이즈가 변경되지 않습니다.
