### ISSUE TITLE
첫 페이지에 들어갈 이미지 변경

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#9]
파일은 메일로 발송하도록 하겠습니다. PDF자료와 AI파일입니다.

**Comment by aanoaa** [comment]
ai 파일이 뭔가요?

여기 코멘트에 파일 첨부할 수 있을걸요

**Comment by aanoaa** [comment]
Adobe Illustrator 문서가 ai 네요.

png 나 jpg 같은 형식으로 주세요.

**Comment by 10001if** [comment]
![default](https://cloud.githubusercontent.com/assets/4696328/13721108/b7c9f4ec-e85e-11e5-9bcf-c2bdbfd546c5.png)
다시 남겨드립니다~ 그리고 오늘부터 만들어 주신 기증프로그램으로 기증신청이 되도록 링크를 변경하였습니다. ^^

**Comment by aanoaa** [comment]
반영하였습니다.
