### ISSUE TITLE
수선 장소에 라이벌 추가

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/donation#90]
수원에 있는 라이벌 양복점에 수선을 지속적으로 맡길 예정입니다.
`라이벌`이라고 추가해 주시면 됩니다.^^

**Comment by MoDoLEE** [comment]
https://github.com/opencloset/opencloset/issues/1203

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
