### ISSUE TITLE
배송주문서 목록을 csv 파일로 내보내기

### ISSUE THREAD

**Issue by 10001if** [opencloset/donation#92]
https://github.com/opencloset/donation/issues/63 본 이슈와 유사합니다.

결제완료된 배송주문서들 중에 발송일이 오늘인 주문서만 추린 뒤 

이름 / 전화번호 / 주소 / 배송메세지 가 입력된 채로 파일을 다운로드 하고자 합니다.

![2017-03-22 4 59 29](https://cloud.githubusercontent.com/assets/4696328/24187656/4b90a6c8-0f21-11e7-8f2a-133315841d02.png)

이름 / 번화번호 / 주소에 관련된 내용은 기존 기증자와 동일하지만 

배송메세지의 경우에는 https://share.theopencloset.net/orders/55385/purchase 페이지에서 보이는 
![2017-03-22 5 01 50](https://cloud.githubusercontent.com/assets/4696328/24187720/92a0007c-0f21-11e7-9efb-8aa135936824.png) 배송메세지가 함께 다운로드 될 수 있도록 요청드립니다.

**Comment by aanoaa** [comment]
어찌됐든 해결되었습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by pingpongworks** [comment]
@aanoaa @10001if 운송장 다운로드 너무 좋은데, 모든 주문서가 다 다운로드 되는게 좀 아쉽네요. **선택박스가 있어서 오늘 날짜 주문서만 선택해서 다운로드**하면 좋을 거 같은데 어려운 작업일까요?

**Comment by 10001if** [comment]
@pingpongworks 착용일을 클릭해서 오늘 날짜만 본 상태에서 다운로드하면 됩니다~

**Comment by pingpongworks** [comment]
아항~ 상희랑 재현이가 그 방법을 모르고 있었네요. 전달할게요~

김소령
OpenCloset / story tailor
010. 5278. 2844
pingpong@theopencloset.net

2017. 4. 17. 오전 10:08 Han manil <notifications@github.com> 작성:
