### ISSUE TITLE
기증의류 폐기 등록시  '비전' 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/donation#93]
기증의류를 정리한 후 폐기해야할 경우 현재는 '옷캔' '비백' 두 군데로 재기증하고 있습니다.  노숙인 자활센터인 '비전트레이닝센터'로도 재기증되고 있으니 추가해주세요. 그동안은 수량이 워낙 적어서 따로 등록하지 않았으나, 기증량도 꾸준해졌고, 비전트레이닝센터에서는 저희가 기증한 의류에 대해서 기부금영수증도 해주고 계셔서 정확하게 보낸 의류수를 집계할 필요가 있습니다.

풀네임은 '비전트레이닝센터' 입니다만, **축약해서 '비전'으로 해주시면 됩니다.**

**Comment by aanoaa** [comment]
https://github.com/opencloset/donation/issues/6#issuecomment-205612142

새옷등록과 동시에 옷캔과 비백으로 상태를 변경하는 기능은 새옷등록이라는 큰이슈에 포함되어서 한번에 처리되었던 것 같습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Schema/issues/55

에서 재활용(xxx), 사용못함 상태가 추가되었습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Common/commit/ed275ed922357c94646d179c14a345b3eb7d9391

**Comment by aanoaa** [comment]
![2017-05-04 14-51-44](https://cloud.githubusercontent.com/assets/170528/25691818/39294696-30d9-11e7-9fa2-7350c9143f3f.png)

새옷등록할때에 비전버튼이 추가되어야 합니다.

**Comment by aanoaa** [comment]
비전이 추가됨에 따라,

- 기증신청서 내역의 등록된 의류정보에 비전의 현황 추가
- 기증현황 안내 SMS 에 비전트레이닝센터에 대한 설명과 현황 추가
- 등록된 의류 현황에 비전현황 추가

가 되어야 합니다.

**Comment by aanoaa** [comment]
`기증현황 안내 SMS` 는 아래와 같은 내용을 포함하고 있습니다.

```
총 기증의류: 벨트 1, 블라우스 8, 코트 1, 자켓 1, 원피스 1, 팬츠 3, 셔츠 4
- 열린옷장 사용의류: 블라우스 3, 코트 1, 팬츠 1
- [옷캔] 재기증 의류: 블라우스 5, 자켓 1, 원피스 1, 팬츠 2, 셔츠 4
옷캔 (http://www.otcan.org)은 의류 재활용을 통해 제3세계 어린이들에게 꿈과 희망을 선물하는 외교부 소관 NGO입니다.
```

비전을 제가 임의로 추가해보았습니다.

```
- [비전] 트레이닝센터 활용 의류: 벨트: 1
비전 (http://www.vtc.or.kr/)은 서울시립 노숙인 재활센터입니다.
```

**Comment by aanoaa** [comment]
비전에 관련된 의류의 마지막 코드를 관리해주어야 합니다.

**Comment by aanoaa** [comment]
따로 관리하는 것이 아니라 재활용의류이거나 사용못하는 의류일때에 의류코드를 업데이트
시켜주어야 합니다.

**Comment by pingpongworks** [comment]
한가지 궁금한게 있습니다. 
위에서 말씀드린바와 같이 매월말 비전에 기증한 의류수를 파악해서 비전 측에 기증내역서를 보내고 기부금 영수증을 발급받아야 합니다. 일정기간 동안 비전에 기증된 의류 종류와 수를 어떻게 파악할수 있을까요?

**Comment by aanoaa** [comment]
> 정확하게 보낸 의류수를 집계할 필요가 있습니다.

이건 제가 못봤습니다.
#82 에서 의류등록날짜를 기록하고자 하는 이슈가 선행되어야 합니다.

이후에는 특정기간동안의 등록된 의류의 수량을 파악할 수 있습니다.
