### ISSUE TITLE
원피스 품목에 대한 재기증 버튼 작동 안함

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/donation#98]
재기증 품목 등록 시
**원피스**에 대해서 옷캔, 비백, 비전, 재활용못함 어떠한 버튼도 정상 동작(등록된 의류에 표시)하지 않습니다.
기증번호 4385 의류 등록하다가 발생했는데, 다른 분도 테스트해 봤는데 동일한 증상입니다.

**Comment by aanoaa** [comment]
새옷등록 할때에 원피스를 옷캔|비백|비전|사용못함으로 분류하지 못합니다.

    [error] Duplicate clothes code: 0O0ID

https://staff.theopencloset.net/clothes/0O0ID 는 폐기된 의류입니다.

아직 발급되지 않은 의류코드가 등록되어 있습니다.
의류코드 발급은 컴피터로 이루어지고 있는데 등록할때에 오타가 있었던 것 같습니다.

``` sql
UPDATE clothes_code SET code = '0O0ID' WHERE category = 'onepiece';
```

쿼리로 해결하였습니다.
